// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: completions.sql

package sqlcstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteCompletion = `-- name: DeleteCompletion :execrows
DELETE FROM completions
WHERE member_id = $1
  AND quest_id = $2
  AND date = $3
`

type DeleteCompletionParams struct {
	MemberID string      `json:"member_id"`
	QuestID  string      `json:"quest_id"`
	Date     pgtype.Date `json:"date"`
}

func (q *Queries) DeleteCompletion(ctx context.Context, arg DeleteCompletionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCompletion, arg.MemberID, arg.QuestID, arg.Date)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCompletion = `-- name: GetCompletion :one
SELECT member_id, quest_id, room_id, date, completed_at, note, updated_at
FROM completions
WHERE member_id = $1
  AND quest_id = $2
  AND date = $3
LIMIT 1
`

type GetCompletionParams struct {
	MemberID string      `json:"member_id"`
	QuestID  string      `json:"quest_id"`
	Date     pgtype.Date `json:"date"`
}

func (q *Queries) GetCompletion(ctx context.Context, arg GetCompletionParams) (*Completion, error) {
	row := q.db.QueryRow(ctx, getCompletion, arg.MemberID, arg.QuestID, arg.Date)
	var i Completion
	err := row.Scan(
		&i.MemberID,
		&i.QuestID,
		&i.RoomID,
		&i.Date,
		&i.CompletedAt,
		&i.Note,
		&i.UpdatedAt,
	)
	return &i, err
}

const listCompletionsByRoomAndDate = `-- name: ListCompletionsByRoomAndDate :many
SELECT member_id, quest_id, room_id, date, completed_at, note, updated_at
FROM completions
WHERE room_id = $1
  AND date = $2
ORDER BY completed_at ASC, member_id ASC, quest_id ASC
`

type ListCompletionsByRoomAndDateParams struct {
	RoomID string      `json:"room_id"`
	Date   pgtype.Date `json:"date"`
}

func (q *Queries) ListCompletionsByRoomAndDate(ctx context.Context, arg ListCompletionsByRoomAndDateParams) ([]*Completion, error) {
	rows, err := q.db.Query(ctx, listCompletionsByRoomAndDate, arg.RoomID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Completion
	for rows.Next() {
		var i Completion
		if err := rows.Scan(
			&i.MemberID,
			&i.QuestID,
			&i.RoomID,
			&i.Date,
			&i.CompletedAt,
			&i.Note,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompletionsByRoomAndDateRange = `-- name: ListCompletionsByRoomAndDateRange :many
SELECT member_id, quest_id, room_id, date, completed_at, note, updated_at
FROM completions
WHERE room_id = $1
  AND date BETWEEN $2 AND $3
  AND ($4::text IS NULL OR quest_id = $4::text)
  AND ($5::text IS NULL OR member_id = $5::text)
ORDER BY date DESC, completed_at DESC, member_id ASC, quest_id ASC
`

type ListCompletionsByRoomAndDateRangeParams struct {
	RoomID   string      `json:"room_id"`
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
	QuestID  pgtype.Text `json:"quest_id"`
	MemberID pgtype.Text `json:"member_id"`
}

func (q *Queries) ListCompletionsByRoomAndDateRange(ctx context.Context, arg ListCompletionsByRoomAndDateRangeParams) ([]*Completion, error) {
	rows, err := q.db.Query(ctx, listCompletionsByRoomAndDateRange,
		arg.RoomID,
		arg.FromDate,
		arg.ToDate,
		arg.QuestID,
		arg.MemberID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Completion
	for rows.Next() {
		var i Completion
		if err := rows.Scan(
			&i.MemberID,
			&i.QuestID,
			&i.RoomID,
			&i.Date,
			&i.CompletedAt,
			&i.Note,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCompletion = `-- name: UpsertCompletion :one
INSERT INTO completions (
  member_id,
  quest_id,
  room_id,
  date,
  completed_at,
  note
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
ON CONFLICT (member_id, quest_id, date)
DO UPDATE
SET
  completed_at = EXCLUDED.completed_at,
  note = EXCLUDED.note
RETURNING member_id, quest_id, room_id, date, completed_at, note, updated_at
`

type UpsertCompletionParams struct {
	MemberID    string             `json:"member_id"`
	QuestID     string             `json:"quest_id"`
	RoomID      string             `json:"room_id"`
	Date        pgtype.Date        `json:"date"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	Note        pgtype.Text        `json:"note"`
}

func (q *Queries) UpsertCompletion(ctx context.Context, arg UpsertCompletionParams) (*Completion, error) {
	row := q.db.QueryRow(ctx, upsertCompletion,
		arg.MemberID,
		arg.QuestID,
		arg.RoomID,
		arg.Date,
		arg.CompletedAt,
		arg.Note,
	)
	var i Completion
	err := row.Scan(
		&i.MemberID,
		&i.QuestID,
		&i.RoomID,
		&i.Date,
		&i.CompletedAt,
		&i.Note,
		&i.UpdatedAt,
	)
	return &i, err
}
