// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: members.sql

package sqlcstore

import (
	"context"
)

const countMembersByRoomID = `-- name: CountMembersByRoomID :one
SELECT COUNT(*)::int AS member_count
FROM members
WHERE room_id = $1
`

func (q *Queries) CountMembersByRoomID(ctx context.Context, roomID string) (int32, error) {
	row := q.db.QueryRow(ctx, countMembersByRoomID, roomID)
	var member_count int32
	err := row.Scan(&member_count)
	return member_count, err
}

const createMember = `-- name: CreateMember :one
INSERT INTO members (
  id,
  room_id,
  nickname,
  role
)
VALUES (
  $1,
  $2,
  $3,
  $4
)
RETURNING id, room_id, nickname, role, joined_at, updated_at
`

type CreateMemberParams struct {
	ID       string     `json:"id"`
	RoomID   string     `json:"room_id"`
	Nickname string     `json:"nickname"`
	Role     MemberRole `json:"role"`
}

func (q *Queries) CreateMember(ctx context.Context, arg CreateMemberParams) (*Member, error) {
	row := q.db.QueryRow(ctx, createMember,
		arg.ID,
		arg.RoomID,
		arg.Nickname,
		arg.Role,
	)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Nickname,
		&i.Role,
		&i.JoinedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deleteMemberByRoomAndID = `-- name: DeleteMemberByRoomAndID :exec
DELETE FROM members
WHERE room_id = $1
  AND id = $2
`

type DeleteMemberByRoomAndIDParams struct {
	RoomID string `json:"room_id"`
	ID     string `json:"id"`
}

func (q *Queries) DeleteMemberByRoomAndID(ctx context.Context, arg DeleteMemberByRoomAndIDParams) error {
	_, err := q.db.Exec(ctx, deleteMemberByRoomAndID, arg.RoomID, arg.ID)
	return err
}

const getLeaderByRoomID = `-- name: GetLeaderByRoomID :one
SELECT id, room_id, nickname, role, joined_at, updated_at
FROM members
WHERE room_id = $1
  AND role = 'leader'
LIMIT 1
`

func (q *Queries) GetLeaderByRoomID(ctx context.Context, roomID string) (*Member, error) {
	row := q.db.QueryRow(ctx, getLeaderByRoomID, roomID)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Nickname,
		&i.Role,
		&i.JoinedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getMemberByID = `-- name: GetMemberByID :one
SELECT id, room_id, nickname, role, joined_at, updated_at
FROM members
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetMemberByID(ctx context.Context, id string) (*Member, error) {
	row := q.db.QueryRow(ctx, getMemberByID, id)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Nickname,
		&i.Role,
		&i.JoinedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getMemberByRoomAndID = `-- name: GetMemberByRoomAndID :one
SELECT id, room_id, nickname, role, joined_at, updated_at
FROM members
WHERE room_id = $1
  AND id = $2
LIMIT 1
`

type GetMemberByRoomAndIDParams struct {
	RoomID string `json:"room_id"`
	ID     string `json:"id"`
}

func (q *Queries) GetMemberByRoomAndID(ctx context.Context, arg GetMemberByRoomAndIDParams) (*Member, error) {
	row := q.db.QueryRow(ctx, getMemberByRoomAndID, arg.RoomID, arg.ID)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Nickname,
		&i.Role,
		&i.JoinedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getMemberByRoomAndNickname = `-- name: GetMemberByRoomAndNickname :one
SELECT id, room_id, nickname, role, joined_at, updated_at
FROM members
WHERE room_id = $1
  AND nickname = $2
LIMIT 1
`

type GetMemberByRoomAndNicknameParams struct {
	RoomID   string `json:"room_id"`
	Nickname string `json:"nickname"`
}

func (q *Queries) GetMemberByRoomAndNickname(ctx context.Context, arg GetMemberByRoomAndNicknameParams) (*Member, error) {
	row := q.db.QueryRow(ctx, getMemberByRoomAndNickname, arg.RoomID, arg.Nickname)
	var i Member
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Nickname,
		&i.Role,
		&i.JoinedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listMembersByRoomID = `-- name: ListMembersByRoomID :many
SELECT id, room_id, nickname, role, joined_at, updated_at
FROM members
WHERE room_id = $1
ORDER BY role ASC, joined_at ASC, id ASC
`

func (q *Queries) ListMembersByRoomID(ctx context.Context, roomID string) ([]*Member, error) {
	rows, err := q.db.Query(ctx, listMembersByRoomID, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*Member
	for rows.Next() {
		var i Member
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.Nickname,
			&i.Role,
			&i.JoinedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
