// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcstore

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type MemberRole string

const (
	MemberRoleLeader MemberRole = "leader"
	MemberRoleMember MemberRole = "member"
)

func (e *MemberRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MemberRole(s)
	case string:
		*e = MemberRole(s)
	default:
		return fmt.Errorf("unsupported scan type for MemberRole: %T", src)
	}
	return nil
}

type NullMemberRole struct {
	MemberRole MemberRole `json:"member_role"`
	Valid      bool       `json:"valid"` // Valid is true if MemberRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMemberRole) Scan(value interface{}) error {
	if value == nil {
		ns.MemberRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MemberRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMemberRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MemberRole), nil
}

type Completion struct {
	MemberID    string             `json:"member_id"`
	QuestID     string             `json:"quest_id"`
	RoomID      string             `json:"room_id"`
	Date        pgtype.Date        `json:"date"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	Note        pgtype.Text        `json:"note"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Member struct {
	ID        string             `json:"id"`
	RoomID    string             `json:"room_id"`
	Nickname  string             `json:"nickname"`
	Role      MemberRole         `json:"role"`
	JoinedAt  pgtype.Timestamptz `json:"joined_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type RecurringQuest struct {
	ID                string             `json:"id"`
	RoomID            string             `json:"room_id"`
	Title             string             `json:"title"`
	Description       string             `json:"description"`
	SortOrder         int32              `json:"sort_order"`
	IsActive          bool               `json:"is_active"`
	CreatedByMemberID string             `json:"created_by_member_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Room struct {
	ID                     string             `json:"id"`
	Name                   string             `json:"name"`
	FinalGoal              string             `json:"final_goal"`
	Timezone               string             `json:"timezone"`
	InviteToken            string             `json:"invite_token"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
	FinalGoalDate          pgtype.Date        `json:"final_goal_date"`
	DailyGoalCutoffPercent int32              `json:"daily_goal_cutoff_percent"`
}

type Session struct {
	ID               int64              `json:"id"`
	MemberID         string             `json:"member_id"`
	RoomID           string             `json:"room_id"`
	SessionTokenHash string             `json:"session_token_hash"`
	IssuedAt         pgtype.Timestamptz `json:"issued_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	LastSeenAt       pgtype.Timestamptz `json:"last_seen_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}
