// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recurring_quests.sql

package sqlcstore

import (
	"context"
)

const createRecurringQuest = `-- name: CreateRecurringQuest :one
INSERT INTO recurring_quests (
  id,
  room_id,
  title,
  description,
  sort_order,
  is_active,
  created_by_member_id
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
)
RETURNING id, room_id, title, description, sort_order, is_active, created_by_member_id, created_at, updated_at
`

type CreateRecurringQuestParams struct {
	ID                string `json:"id"`
	RoomID            string `json:"room_id"`
	Title             string `json:"title"`
	Description       string `json:"description"`
	SortOrder         int32  `json:"sort_order"`
	IsActive          bool   `json:"is_active"`
	CreatedByMemberID string `json:"created_by_member_id"`
}

func (q *Queries) CreateRecurringQuest(ctx context.Context, arg CreateRecurringQuestParams) (*RecurringQuest, error) {
	row := q.db.QueryRow(ctx, createRecurringQuest,
		arg.ID,
		arg.RoomID,
		arg.Title,
		arg.Description,
		arg.SortOrder,
		arg.IsActive,
		arg.CreatedByMemberID,
	)
	var i RecurringQuest
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Title,
		&i.Description,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedByMemberID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getNextRecurringQuestSortOrder = `-- name: GetNextRecurringQuestSortOrder :one
SELECT COALESCE(MAX(sort_order) + 1, 0)::int AS next_sort_order
FROM recurring_quests
WHERE room_id = $1
`

func (q *Queries) GetNextRecurringQuestSortOrder(ctx context.Context, roomID string) (int32, error) {
	row := q.db.QueryRow(ctx, getNextRecurringQuestSortOrder, roomID)
	var next_sort_order int32
	err := row.Scan(&next_sort_order)
	return next_sort_order, err
}

const getRecurringQuestByID = `-- name: GetRecurringQuestByID :one
SELECT id, room_id, title, description, sort_order, is_active, created_by_member_id, created_at, updated_at
FROM recurring_quests
WHERE room_id = $1
  AND id = $2
LIMIT 1
`

type GetRecurringQuestByIDParams struct {
	RoomID string `json:"room_id"`
	ID     string `json:"id"`
}

func (q *Queries) GetRecurringQuestByID(ctx context.Context, arg GetRecurringQuestByIDParams) (*RecurringQuest, error) {
	row := q.db.QueryRow(ctx, getRecurringQuestByID, arg.RoomID, arg.ID)
	var i RecurringQuest
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Title,
		&i.Description,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedByMemberID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listActiveRecurringQuestsByRoomID = `-- name: ListActiveRecurringQuestsByRoomID :many
SELECT id, room_id, title, description, sort_order, is_active, created_by_member_id, created_at, updated_at
FROM recurring_quests
WHERE room_id = $1
  AND is_active = TRUE
ORDER BY sort_order ASC, created_at ASC, id ASC
`

func (q *Queries) ListActiveRecurringQuestsByRoomID(ctx context.Context, roomID string) ([]*RecurringQuest, error) {
	rows, err := q.db.Query(ctx, listActiveRecurringQuestsByRoomID, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*RecurringQuest
	for rows.Next() {
		var i RecurringQuest
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.Title,
			&i.Description,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedByMemberID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurringQuestsByRoomID = `-- name: ListRecurringQuestsByRoomID :many
SELECT id, room_id, title, description, sort_order, is_active, created_by_member_id, created_at, updated_at
FROM recurring_quests
WHERE room_id = $1
ORDER BY sort_order ASC, created_at ASC, id ASC
`

func (q *Queries) ListRecurringQuestsByRoomID(ctx context.Context, roomID string) ([]*RecurringQuest, error) {
	rows, err := q.db.Query(ctx, listRecurringQuestsByRoomID, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*RecurringQuest
	for rows.Next() {
		var i RecurringQuest
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.Title,
			&i.Description,
			&i.SortOrder,
			&i.IsActive,
			&i.CreatedByMemberID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRecurringQuest = `-- name: UpdateRecurringQuest :one
UPDATE recurring_quests
SET
  title = $3,
  description = $4,
  sort_order = $5,
  is_active = $6
WHERE room_id = $1
  AND id = $2
RETURNING id, room_id, title, description, sort_order, is_active, created_by_member_id, created_at, updated_at
`

type UpdateRecurringQuestParams struct {
	RoomID      string `json:"room_id"`
	ID          string `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
	SortOrder   int32  `json:"sort_order"`
	IsActive    bool   `json:"is_active"`
}

func (q *Queries) UpdateRecurringQuest(ctx context.Context, arg UpdateRecurringQuestParams) (*RecurringQuest, error) {
	row := q.db.QueryRow(ctx, updateRecurringQuest,
		arg.RoomID,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.SortOrder,
		arg.IsActive,
	)
	var i RecurringQuest
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.Title,
		&i.Description,
		&i.SortOrder,
		&i.IsActive,
		&i.CreatedByMemberID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}
