// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rooms.sql

package sqlcstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeCurrentRoomDailyGoalCutoffRevision = `-- name: CloseCurrentRoomDailyGoalCutoffRevision :exec
UPDATE room_daily_goal_cutoff_revisions
SET ended_at = $2
WHERE room_id = $1
  AND ended_at IS NULL
`

type CloseCurrentRoomDailyGoalCutoffRevisionParams struct {
	RoomID  string             `json:"room_id"`
	EndedAt pgtype.Timestamptz `json:"ended_at"`
}

func (q *Queries) CloseCurrentRoomDailyGoalCutoffRevision(ctx context.Context, arg CloseCurrentRoomDailyGoalCutoffRevisionParams) error {
	_, err := q.db.Exec(ctx, closeCurrentRoomDailyGoalCutoffRevision, arg.RoomID, arg.EndedAt)
	return err
}

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (
  id,
  name,
  final_goal,
  final_goal_date,
  visibility,
  timezone,
  invite_token
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
)
RETURNING id, name, final_goal, timezone, invite_token, created_at, updated_at, final_goal_date, daily_goal_cutoff_percent, visibility
`

type CreateRoomParams struct {
	ID            string         `json:"id"`
	Name          string         `json:"name"`
	FinalGoal     string         `json:"final_goal"`
	FinalGoalDate pgtype.Date    `json:"final_goal_date"`
	Visibility    RoomVisibility `json:"visibility"`
	Timezone      string         `json:"timezone"`
	InviteToken   string         `json:"invite_token"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (*Room, error) {
	row := q.db.QueryRow(ctx, createRoom,
		arg.ID,
		arg.Name,
		arg.FinalGoal,
		arg.FinalGoalDate,
		arg.Visibility,
		arg.Timezone,
		arg.InviteToken,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FinalGoal,
		&i.Timezone,
		&i.InviteToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinalGoalDate,
		&i.DailyGoalCutoffPercent,
		&i.Visibility,
	)
	return &i, err
}

const createRoomDailyGoalCutoffRevision = `-- name: CreateRoomDailyGoalCutoffRevision :one
INSERT INTO room_daily_goal_cutoff_revisions (
  room_id,
  cutoff_percent,
  started_at
)
VALUES (
  $1,
  $2,
  $3
)
RETURNING id, room_id, cutoff_percent, started_at, ended_at, created_at
`

type CreateRoomDailyGoalCutoffRevisionParams struct {
	RoomID        string             `json:"room_id"`
	CutoffPercent int32              `json:"cutoff_percent"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
}

func (q *Queries) CreateRoomDailyGoalCutoffRevision(ctx context.Context, arg CreateRoomDailyGoalCutoffRevisionParams) (*RoomDailyGoalCutoffRevision, error) {
	row := q.db.QueryRow(ctx, createRoomDailyGoalCutoffRevision, arg.RoomID, arg.CutoffPercent, arg.StartedAt)
	var i RoomDailyGoalCutoffRevision
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.CutoffPercent,
		&i.StartedAt,
		&i.EndedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const getRoomByID = `-- name: GetRoomByID :one
SELECT id, name, final_goal, timezone, invite_token, created_at, updated_at, final_goal_date, daily_goal_cutoff_percent, visibility
FROM rooms
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetRoomByID(ctx context.Context, id string) (*Room, error) {
	row := q.db.QueryRow(ctx, getRoomByID, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FinalGoal,
		&i.Timezone,
		&i.InviteToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinalGoalDate,
		&i.DailyGoalCutoffPercent,
		&i.Visibility,
	)
	return &i, err
}

const getRoomByInviteToken = `-- name: GetRoomByInviteToken :one
SELECT id, name, final_goal, timezone, invite_token, created_at, updated_at, final_goal_date, daily_goal_cutoff_percent, visibility
FROM rooms
WHERE invite_token = $1
LIMIT 1
`

func (q *Queries) GetRoomByInviteToken(ctx context.Context, inviteToken string) (*Room, error) {
	row := q.db.QueryRow(ctx, getRoomByInviteToken, inviteToken)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FinalGoal,
		&i.Timezone,
		&i.InviteToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinalGoalDate,
		&i.DailyGoalCutoffPercent,
		&i.Visibility,
	)
	return &i, err
}

const getRoomDailyGoalCutoffAtTimestamp = `-- name: GetRoomDailyGoalCutoffAtTimestamp :one
SELECT cutoff_percent
FROM room_daily_goal_cutoff_revisions
WHERE room_id = $1
  AND started_at < $2
  AND (ended_at IS NULL OR ended_at >= $2)
ORDER BY started_at DESC
LIMIT 1
`

type GetRoomDailyGoalCutoffAtTimestampParams struct {
	RoomID    string             `json:"room_id"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
}

func (q *Queries) GetRoomDailyGoalCutoffAtTimestamp(ctx context.Context, arg GetRoomDailyGoalCutoffAtTimestampParams) (int32, error) {
	row := q.db.QueryRow(ctx, getRoomDailyGoalCutoffAtTimestamp, arg.RoomID, arg.StartedAt)
	var cutoff_percent int32
	err := row.Scan(&cutoff_percent)
	return cutoff_percent, err
}

const getRoomSummaryByID = `-- name: GetRoomSummaryByID :one
SELECT
  r.id,
  r.name,
  r.final_goal,
  r.final_goal_date,
  r.daily_goal_cutoff_percent,
  r.visibility,
  r.timezone,
  r.invite_token,
  (
    SELECT m.id
    FROM members m
    WHERE m.room_id = r.id
      AND m.role = 'leader'
      AND m.removed_at IS NULL
    LIMIT 1
  ) AS leader_member_id,
  (
    SELECT COUNT(*)::int
    FROM members m
    WHERE m.room_id = r.id
      AND m.removed_at IS NULL
  ) AS member_count,
  r.created_at,
  r.updated_at
FROM rooms r
WHERE r.id = $1
LIMIT 1
`

type GetRoomSummaryByIDRow struct {
	ID                     string             `json:"id"`
	Name                   string             `json:"name"`
	FinalGoal              string             `json:"final_goal"`
	FinalGoalDate          pgtype.Date        `json:"final_goal_date"`
	DailyGoalCutoffPercent int32              `json:"daily_goal_cutoff_percent"`
	Visibility             RoomVisibility     `json:"visibility"`
	Timezone               string             `json:"timezone"`
	InviteToken            string             `json:"invite_token"`
	LeaderMemberID         string             `json:"leader_member_id"`
	MemberCount            int32              `json:"member_count"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetRoomSummaryByID(ctx context.Context, id string) (*GetRoomSummaryByIDRow, error) {
	row := q.db.QueryRow(ctx, getRoomSummaryByID, id)
	var i GetRoomSummaryByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FinalGoal,
		&i.FinalGoalDate,
		&i.DailyGoalCutoffPercent,
		&i.Visibility,
		&i.Timezone,
		&i.InviteToken,
		&i.LeaderMemberID,
		&i.MemberCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getRoomSummaryByInviteToken = `-- name: GetRoomSummaryByInviteToken :one
SELECT
  r.id,
  r.name,
  r.final_goal,
  r.final_goal_date,
  r.daily_goal_cutoff_percent,
  r.visibility,
  r.timezone,
  r.invite_token,
  (
    SELECT m.id
    FROM members m
    WHERE m.room_id = r.id
      AND m.role = 'leader'
      AND m.removed_at IS NULL
    LIMIT 1
  ) AS leader_member_id,
  (
    SELECT COUNT(*)::int
    FROM members m
    WHERE m.room_id = r.id
      AND m.removed_at IS NULL
  ) AS member_count,
  r.created_at,
  r.updated_at
FROM rooms r
WHERE r.invite_token = $1
LIMIT 1
`

type GetRoomSummaryByInviteTokenRow struct {
	ID                     string             `json:"id"`
	Name                   string             `json:"name"`
	FinalGoal              string             `json:"final_goal"`
	FinalGoalDate          pgtype.Date        `json:"final_goal_date"`
	DailyGoalCutoffPercent int32              `json:"daily_goal_cutoff_percent"`
	Visibility             RoomVisibility     `json:"visibility"`
	Timezone               string             `json:"timezone"`
	InviteToken            string             `json:"invite_token"`
	LeaderMemberID         string             `json:"leader_member_id"`
	MemberCount            int32              `json:"member_count"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetRoomSummaryByInviteToken(ctx context.Context, inviteToken string) (*GetRoomSummaryByInviteTokenRow, error) {
	row := q.db.QueryRow(ctx, getRoomSummaryByInviteToken, inviteToken)
	var i GetRoomSummaryByInviteTokenRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FinalGoal,
		&i.FinalGoalDate,
		&i.DailyGoalCutoffPercent,
		&i.Visibility,
		&i.Timezone,
		&i.InviteToken,
		&i.LeaderMemberID,
		&i.MemberCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listRoomSummaries = `-- name: ListRoomSummaries :many
SELECT
  r.id,
  r.name,
  r.final_goal,
  r.final_goal_date,
  r.daily_goal_cutoff_percent,
  r.visibility,
  r.timezone,
  r.invite_token,
  (
    SELECT m.id
    FROM members m
    WHERE m.room_id = r.id
      AND m.role = 'leader'
      AND m.removed_at IS NULL
    LIMIT 1
  ) AS leader_member_id,
  (
    SELECT COUNT(*)::int
    FROM members m
    WHERE m.room_id = r.id
      AND m.removed_at IS NULL
  ) AS member_count,
  r.created_at,
  r.updated_at
FROM rooms r
WHERE r.visibility = 'public'
ORDER BY r.created_at DESC
`

type ListRoomSummariesRow struct {
	ID                     string             `json:"id"`
	Name                   string             `json:"name"`
	FinalGoal              string             `json:"final_goal"`
	FinalGoalDate          pgtype.Date        `json:"final_goal_date"`
	DailyGoalCutoffPercent int32              `json:"daily_goal_cutoff_percent"`
	Visibility             RoomVisibility     `json:"visibility"`
	Timezone               string             `json:"timezone"`
	InviteToken            string             `json:"invite_token"`
	LeaderMemberID         string             `json:"leader_member_id"`
	MemberCount            int32              `json:"member_count"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListRoomSummaries(ctx context.Context) ([]*ListRoomSummariesRow, error) {
	rows, err := q.db.Query(ctx, listRoomSummaries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListRoomSummariesRow
	for rows.Next() {
		var i ListRoomSummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FinalGoal,
			&i.FinalGoalDate,
			&i.DailyGoalCutoffPercent,
			&i.Visibility,
			&i.Timezone,
			&i.InviteToken,
			&i.LeaderMemberID,
			&i.MemberCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rotateInviteToken = `-- name: RotateInviteToken :one
UPDATE rooms
SET invite_token = $2
WHERE id = $1
RETURNING id, name, final_goal, timezone, invite_token, created_at, updated_at, final_goal_date, daily_goal_cutoff_percent, visibility
`

type RotateInviteTokenParams struct {
	ID          string `json:"id"`
	InviteToken string `json:"invite_token"`
}

func (q *Queries) RotateInviteToken(ctx context.Context, arg RotateInviteTokenParams) (*Room, error) {
	row := q.db.QueryRow(ctx, rotateInviteToken, arg.ID, arg.InviteToken)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FinalGoal,
		&i.Timezone,
		&i.InviteToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinalGoalDate,
		&i.DailyGoalCutoffPercent,
		&i.Visibility,
	)
	return &i, err
}

const updateRoom = `-- name: UpdateRoom :one
UPDATE rooms
SET
  name = $2,
  final_goal = $3,
  final_goal_date = $4,
  daily_goal_cutoff_percent = $5,
  visibility = $6,
  timezone = $7
WHERE id = $1
RETURNING id, name, final_goal, timezone, invite_token, created_at, updated_at, final_goal_date, daily_goal_cutoff_percent, visibility
`

type UpdateRoomParams struct {
	ID                     string         `json:"id"`
	Name                   string         `json:"name"`
	FinalGoal              string         `json:"final_goal"`
	FinalGoalDate          pgtype.Date    `json:"final_goal_date"`
	DailyGoalCutoffPercent int32          `json:"daily_goal_cutoff_percent"`
	Visibility             RoomVisibility `json:"visibility"`
	Timezone               string         `json:"timezone"`
}

func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) (*Room, error) {
	row := q.db.QueryRow(ctx, updateRoom,
		arg.ID,
		arg.Name,
		arg.FinalGoal,
		arg.FinalGoalDate,
		arg.DailyGoalCutoffPercent,
		arg.Visibility,
		arg.Timezone,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FinalGoal,
		&i.Timezone,
		&i.InviteToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinalGoalDate,
		&i.DailyGoalCutoffPercent,
		&i.Visibility,
	)
	return &i, err
}
