// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: rooms.sql

package sqlcstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRoom = `-- name: CreateRoom :one
INSERT INTO rooms (
  id,
  name,
  final_goal,
  final_goal_date,
  timezone,
  invite_token
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
RETURNING id, name, final_goal, timezone, invite_token, created_at, updated_at, final_goal_date, daily_goal_cutoff_percent
`

type CreateRoomParams struct {
	ID            string      `json:"id"`
	Name          string      `json:"name"`
	FinalGoal     string      `json:"final_goal"`
	FinalGoalDate pgtype.Date `json:"final_goal_date"`
	Timezone      string      `json:"timezone"`
	InviteToken   string      `json:"invite_token"`
}

func (q *Queries) CreateRoom(ctx context.Context, arg CreateRoomParams) (*Room, error) {
	row := q.db.QueryRow(ctx, createRoom,
		arg.ID,
		arg.Name,
		arg.FinalGoal,
		arg.FinalGoalDate,
		arg.Timezone,
		arg.InviteToken,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FinalGoal,
		&i.Timezone,
		&i.InviteToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinalGoalDate,
		&i.DailyGoalCutoffPercent,
	)
	return &i, err
}

const getRoomByID = `-- name: GetRoomByID :one
SELECT id, name, final_goal, timezone, invite_token, created_at, updated_at, final_goal_date, daily_goal_cutoff_percent
FROM rooms
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetRoomByID(ctx context.Context, id string) (*Room, error) {
	row := q.db.QueryRow(ctx, getRoomByID, id)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FinalGoal,
		&i.Timezone,
		&i.InviteToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinalGoalDate,
		&i.DailyGoalCutoffPercent,
	)
	return &i, err
}

const getRoomByInviteToken = `-- name: GetRoomByInviteToken :one
SELECT id, name, final_goal, timezone, invite_token, created_at, updated_at, final_goal_date, daily_goal_cutoff_percent
FROM rooms
WHERE invite_token = $1
LIMIT 1
`

func (q *Queries) GetRoomByInviteToken(ctx context.Context, inviteToken string) (*Room, error) {
	row := q.db.QueryRow(ctx, getRoomByInviteToken, inviteToken)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FinalGoal,
		&i.Timezone,
		&i.InviteToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinalGoalDate,
		&i.DailyGoalCutoffPercent,
	)
	return &i, err
}

const getRoomSummaryByID = `-- name: GetRoomSummaryByID :one
SELECT
  r.id,
  r.name,
  r.final_goal,
  r.final_goal_date,
  r.daily_goal_cutoff_percent,
  r.timezone,
  r.invite_token,
  (
    SELECT m.id
    FROM members m
    WHERE m.room_id = r.id
      AND m.role = 'leader'
    LIMIT 1
  ) AS leader_member_id,
  (
    SELECT COUNT(*)::int
    FROM members m
    WHERE m.room_id = r.id
  ) AS member_count,
  r.created_at,
  r.updated_at
FROM rooms r
WHERE r.id = $1
LIMIT 1
`

type GetRoomSummaryByIDRow struct {
	ID                     string             `json:"id"`
	Name                   string             `json:"name"`
	FinalGoal              string             `json:"final_goal"`
	FinalGoalDate          pgtype.Date        `json:"final_goal_date"`
	DailyGoalCutoffPercent int32              `json:"daily_goal_cutoff_percent"`
	Timezone               string             `json:"timezone"`
	InviteToken            string             `json:"invite_token"`
	LeaderMemberID         string             `json:"leader_member_id"`
	MemberCount            int32              `json:"member_count"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetRoomSummaryByID(ctx context.Context, id string) (*GetRoomSummaryByIDRow, error) {
	row := q.db.QueryRow(ctx, getRoomSummaryByID, id)
	var i GetRoomSummaryByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FinalGoal,
		&i.FinalGoalDate,
		&i.DailyGoalCutoffPercent,
		&i.Timezone,
		&i.InviteToken,
		&i.LeaderMemberID,
		&i.MemberCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getRoomSummaryByInviteToken = `-- name: GetRoomSummaryByInviteToken :one
SELECT
  r.id,
  r.name,
  r.final_goal,
  r.final_goal_date,
  r.daily_goal_cutoff_percent,
  r.timezone,
  r.invite_token,
  (
    SELECT m.id
    FROM members m
    WHERE m.room_id = r.id
      AND m.role = 'leader'
    LIMIT 1
  ) AS leader_member_id,
  (
    SELECT COUNT(*)::int
    FROM members m
    WHERE m.room_id = r.id
  ) AS member_count,
  r.created_at,
  r.updated_at
FROM rooms r
WHERE r.invite_token = $1
LIMIT 1
`

type GetRoomSummaryByInviteTokenRow struct {
	ID                     string             `json:"id"`
	Name                   string             `json:"name"`
	FinalGoal              string             `json:"final_goal"`
	FinalGoalDate          pgtype.Date        `json:"final_goal_date"`
	DailyGoalCutoffPercent int32              `json:"daily_goal_cutoff_percent"`
	Timezone               string             `json:"timezone"`
	InviteToken            string             `json:"invite_token"`
	LeaderMemberID         string             `json:"leader_member_id"`
	MemberCount            int32              `json:"member_count"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetRoomSummaryByInviteToken(ctx context.Context, inviteToken string) (*GetRoomSummaryByInviteTokenRow, error) {
	row := q.db.QueryRow(ctx, getRoomSummaryByInviteToken, inviteToken)
	var i GetRoomSummaryByInviteTokenRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FinalGoal,
		&i.FinalGoalDate,
		&i.DailyGoalCutoffPercent,
		&i.Timezone,
		&i.InviteToken,
		&i.LeaderMemberID,
		&i.MemberCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const listRoomSummaries = `-- name: ListRoomSummaries :many
SELECT
  r.id,
  r.name,
  r.final_goal,
  r.final_goal_date,
  r.daily_goal_cutoff_percent,
  r.timezone,
  r.invite_token,
  (
    SELECT m.id
    FROM members m
    WHERE m.room_id = r.id
      AND m.role = 'leader'
    LIMIT 1
  ) AS leader_member_id,
  (
    SELECT COUNT(*)::int
    FROM members m
    WHERE m.room_id = r.id
  ) AS member_count,
  r.created_at,
  r.updated_at
FROM rooms r
ORDER BY r.created_at DESC
`

type ListRoomSummariesRow struct {
	ID                     string             `json:"id"`
	Name                   string             `json:"name"`
	FinalGoal              string             `json:"final_goal"`
	FinalGoalDate          pgtype.Date        `json:"final_goal_date"`
	DailyGoalCutoffPercent int32              `json:"daily_goal_cutoff_percent"`
	Timezone               string             `json:"timezone"`
	InviteToken            string             `json:"invite_token"`
	LeaderMemberID         string             `json:"leader_member_id"`
	MemberCount            int32              `json:"member_count"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	UpdatedAt              pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListRoomSummaries(ctx context.Context) ([]*ListRoomSummariesRow, error) {
	rows, err := q.db.Query(ctx, listRoomSummaries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*ListRoomSummariesRow
	for rows.Next() {
		var i ListRoomSummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.FinalGoal,
			&i.FinalGoalDate,
			&i.DailyGoalCutoffPercent,
			&i.Timezone,
			&i.InviteToken,
			&i.LeaderMemberID,
			&i.MemberCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rotateInviteToken = `-- name: RotateInviteToken :one
UPDATE rooms
SET invite_token = $2
WHERE id = $1
RETURNING id, name, final_goal, timezone, invite_token, created_at, updated_at, final_goal_date, daily_goal_cutoff_percent
`

type RotateInviteTokenParams struct {
	ID          string `json:"id"`
	InviteToken string `json:"invite_token"`
}

func (q *Queries) RotateInviteToken(ctx context.Context, arg RotateInviteTokenParams) (*Room, error) {
	row := q.db.QueryRow(ctx, rotateInviteToken, arg.ID, arg.InviteToken)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FinalGoal,
		&i.Timezone,
		&i.InviteToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinalGoalDate,
		&i.DailyGoalCutoffPercent,
	)
	return &i, err
}

const updateRoom = `-- name: UpdateRoom :one
UPDATE rooms
SET
  name = $2,
  final_goal = $3,
  final_goal_date = $4,
  daily_goal_cutoff_percent = $5,
  timezone = $6
WHERE id = $1
RETURNING id, name, final_goal, timezone, invite_token, created_at, updated_at, final_goal_date, daily_goal_cutoff_percent
`

type UpdateRoomParams struct {
	ID                     string      `json:"id"`
	Name                   string      `json:"name"`
	FinalGoal              string      `json:"final_goal"`
	FinalGoalDate          pgtype.Date `json:"final_goal_date"`
	DailyGoalCutoffPercent int32       `json:"daily_goal_cutoff_percent"`
	Timezone               string      `json:"timezone"`
}

func (q *Queries) UpdateRoom(ctx context.Context, arg UpdateRoomParams) (*Room, error) {
	row := q.db.QueryRow(ctx, updateRoom,
		arg.ID,
		arg.Name,
		arg.FinalGoal,
		arg.FinalGoalDate,
		arg.DailyGoalCutoffPercent,
		arg.Timezone,
	)
	var i Room
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.FinalGoal,
		&i.Timezone,
		&i.InviteToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.FinalGoalDate,
		&i.DailyGoalCutoffPercent,
	)
	return &i, err
}
