// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package sqlcstore

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (
  member_id,
  room_id,
  session_token_hash,
  issued_at,
  expires_at,
  last_seen_at
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6
)
RETURNING id, member_id, room_id, session_token_hash, issued_at, expires_at, last_seen_at, revoked_at, created_at
`

type CreateSessionParams struct {
	MemberID         string             `json:"member_id"`
	RoomID           string             `json:"room_id"`
	SessionTokenHash string             `json:"session_token_hash"`
	IssuedAt         pgtype.Timestamptz `json:"issued_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	LastSeenAt       pgtype.Timestamptz `json:"last_seen_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (*Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.MemberID,
		arg.RoomID,
		arg.SessionTokenHash,
		arg.IssuedAt,
		arg.ExpiresAt,
		arg.LastSeenAt,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.RoomID,
		&i.SessionTokenHash,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions
WHERE expires_at <= $1
   OR revoked_at IS NOT NULL
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions, expiresAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActiveSessionAuthContextByTokenHash = `-- name: GetActiveSessionAuthContextByTokenHash :one
SELECT
  s.id AS session_id,
  s.member_id,
  s.room_id,
  s.session_token_hash,
  s.issued_at,
  s.expires_at,
  s.last_seen_at,
  s.revoked_at,
  m.nickname,
  m.role,
  m.joined_at,
  r.name AS room_name,
  r.final_goal,
  r.daily_goal_cutoff_percent,
  r.timezone,
  r.invite_token
FROM sessions s
JOIN members m
  ON m.id = s.member_id
 AND m.room_id = s.room_id
JOIN rooms r
  ON r.id = s.room_id
WHERE s.session_token_hash = $1
  AND s.revoked_at IS NULL
  AND s.expires_at > NOW()
LIMIT 1
`

type GetActiveSessionAuthContextByTokenHashRow struct {
	SessionID              int64              `json:"session_id"`
	MemberID               string             `json:"member_id"`
	RoomID                 string             `json:"room_id"`
	SessionTokenHash       string             `json:"session_token_hash"`
	IssuedAt               pgtype.Timestamptz `json:"issued_at"`
	ExpiresAt              pgtype.Timestamptz `json:"expires_at"`
	LastSeenAt             pgtype.Timestamptz `json:"last_seen_at"`
	RevokedAt              pgtype.Timestamptz `json:"revoked_at"`
	Nickname               string             `json:"nickname"`
	Role                   MemberRole         `json:"role"`
	JoinedAt               pgtype.Timestamptz `json:"joined_at"`
	RoomName               string             `json:"room_name"`
	FinalGoal              string             `json:"final_goal"`
	DailyGoalCutoffPercent int32              `json:"daily_goal_cutoff_percent"`
	Timezone               string             `json:"timezone"`
	InviteToken            string             `json:"invite_token"`
}

func (q *Queries) GetActiveSessionAuthContextByTokenHash(ctx context.Context, sessionTokenHash string) (*GetActiveSessionAuthContextByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getActiveSessionAuthContextByTokenHash, sessionTokenHash)
	var i GetActiveSessionAuthContextByTokenHashRow
	err := row.Scan(
		&i.SessionID,
		&i.MemberID,
		&i.RoomID,
		&i.SessionTokenHash,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.Nickname,
		&i.Role,
		&i.JoinedAt,
		&i.RoomName,
		&i.FinalGoal,
		&i.DailyGoalCutoffPercent,
		&i.Timezone,
		&i.InviteToken,
	)
	return &i, err
}

const getActiveSessionByTokenHash = `-- name: GetActiveSessionByTokenHash :one
SELECT id, member_id, room_id, session_token_hash, issued_at, expires_at, last_seen_at, revoked_at, created_at
FROM sessions
WHERE session_token_hash = $1
  AND revoked_at IS NULL
  AND expires_at > NOW()
LIMIT 1
`

func (q *Queries) GetActiveSessionByTokenHash(ctx context.Context, sessionTokenHash string) (*Session, error) {
	row := q.db.QueryRow(ctx, getActiveSessionByTokenHash, sessionTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.RoomID,
		&i.SessionTokenHash,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, member_id, room_id, session_token_hash, issued_at, expires_at, last_seen_at, revoked_at, created_at
FROM sessions
WHERE session_token_hash = $1
LIMIT 1
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, sessionTokenHash string) (*Session, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, sessionTokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.RoomID,
		&i.SessionTokenHash,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return &i, err
}

const revokeSessionByTokenHash = `-- name: RevokeSessionByTokenHash :exec
UPDATE sessions
SET revoked_at = $2
WHERE session_token_hash = $1
  AND revoked_at IS NULL
`

type RevokeSessionByTokenHashParams struct {
	SessionTokenHash string             `json:"session_token_hash"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) RevokeSessionByTokenHash(ctx context.Context, arg RevokeSessionByTokenHashParams) error {
	_, err := q.db.Exec(ctx, revokeSessionByTokenHash, arg.SessionTokenHash, arg.RevokedAt)
	return err
}

const revokeSessionsByMemberID = `-- name: RevokeSessionsByMemberID :exec
UPDATE sessions
SET revoked_at = $2
WHERE member_id = $1
  AND revoked_at IS NULL
`

type RevokeSessionsByMemberIDParams struct {
	MemberID  string             `json:"member_id"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) RevokeSessionsByMemberID(ctx context.Context, arg RevokeSessionsByMemberIDParams) error {
	_, err := q.db.Exec(ctx, revokeSessionsByMemberID, arg.MemberID, arg.RevokedAt)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions
SET last_seen_at = $2
WHERE session_token_hash = $1
`

type TouchSessionParams struct {
	SessionTokenHash string             `json:"session_token_hash"`
	LastSeenAt       pgtype.Timestamptz `json:"last_seen_at"`
}

func (q *Queries) TouchSession(ctx context.Context, arg TouchSessionParams) error {
	_, err := q.db.Exec(ctx, touchSession, arg.SessionTokenHash, arg.LastSeenAt)
	return err
}
