//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// 헬스 체크
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// 초대 링크 정보 조회
	// (GET /v1/invites/{inviteToken})
	GetInviteSummary(w http.ResponseWriter, r *http.Request, inviteToken string)
	// 초대 링크로 최초 참가
	// (POST /v1/invites/{inviteToken}/members)
	JoinInviteAsMember(w http.ResponseWriter, r *http.Request, inviteToken string)
	// 공개 방 목록 조회
	// (GET /v1/rooms)
	ListRooms(w http.ResponseWriter, r *http.Request)
	// 방 생성
	// (POST /v1/rooms)
	CreateRoom(w http.ResponseWriter, r *http.Request)
	// 방 대시보드 조회
	// (GET /v1/rooms/{roomId})
	GetRoomDashboard(w http.ResponseWriter, r *http.Request, roomId string)
	// 방 이름, 최종 목표 또는 최종 목표 날짜 수정
	// (PATCH /v1/rooms/{roomId})
	UpdateRoom(w http.ResponseWriter, r *http.Request, roomId string)
	// 날짜 범위별 완료 기록 조회
	// (GET /v1/rooms/{roomId}/completions)
	ListCompletions(w http.ResponseWriter, r *http.Request, roomId string, params ListCompletionsParams)
	// 특정 날짜의 방 상태 조회
	// (GET /v1/rooms/{roomId}/daily-status/{date})
	GetRoomDailyStatus(w http.ResponseWriter, r *http.Request, roomId string, date openapi_types.Date)
	// 초대 링크 재발급
	// (POST /v1/rooms/{roomId}/invite-token:rotate)
	RotateInviteToken(w http.ResponseWriter, r *http.Request, roomId string)
	// 방 멤버 강퇴
	// (DELETE /v1/rooms/{roomId}/members/{memberId})
	KickRoomMember(w http.ResponseWriter, r *http.Request, roomId string, memberId string)
	// 반복 퀘스트 목록 조회
	// (GET /v1/rooms/{roomId}/recurring-quests)
	ListRecurringQuests(w http.ResponseWriter, r *http.Request, roomId string)
	// 반복 퀘스트 생성
	// (POST /v1/rooms/{roomId}/recurring-quests)
	CreateRecurringQuest(w http.ResponseWriter, r *http.Request, roomId string)
	// 반복 퀘스트 수정
	// (PATCH /v1/rooms/{roomId}/recurring-quests/{questId})
	UpdateRecurringQuest(w http.ResponseWriter, r *http.Request, roomId string, questId string)
	// 내 완료 기록 취소
	// (DELETE /v1/rooms/{roomId}/recurring-quests/{questId}/completions/{date})
	DeleteMyQuestCompletion(w http.ResponseWriter, r *http.Request, roomId string, questId string, date openapi_types.Date)
	// 내 반복 퀘스트 완료 처리
	// (PUT /v1/rooms/{roomId}/recurring-quests/{questId}/completions/{date})
	PutMyQuestCompletion(w http.ResponseWriter, r *http.Request, roomId string, questId string, date openapi_types.Date)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetInviteSummary operation middleware
func (siw *ServerInterfaceWrapper) GetInviteSummary(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "inviteToken" -------------
	var inviteToken string

	err = runtime.BindStyledParameterWithOptions("simple", "inviteToken", r.PathValue("inviteToken"), &inviteToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "inviteToken", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetInviteSummary(w, r, inviteToken)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// JoinInviteAsMember operation middleware
func (siw *ServerInterfaceWrapper) JoinInviteAsMember(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "inviteToken" -------------
	var inviteToken string

	err = runtime.BindStyledParameterWithOptions("simple", "inviteToken", r.PathValue("inviteToken"), &inviteToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "inviteToken", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.JoinInviteAsMember(w, r, inviteToken)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRooms operation middleware
func (siw *ServerInterfaceWrapper) ListRooms(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRooms(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateRoom operation middleware
func (siw *ServerInterfaceWrapper) CreateRoom(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateRoom(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRoomDashboard operation middleware
func (siw *ServerInterfaceWrapper) GetRoomDashboard(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "roomId" -------------
	var roomId string

	err = runtime.BindStyledParameterWithOptions("simple", "roomId", r.PathValue("roomId"), &roomId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "roomId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRoomDashboard(w, r, roomId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateRoom operation middleware
func (siw *ServerInterfaceWrapper) UpdateRoom(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "roomId" -------------
	var roomId string

	err = runtime.BindStyledParameterWithOptions("simple", "roomId", r.PathValue("roomId"), &roomId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "roomId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateRoom(w, r, roomId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCompletions operation middleware
func (siw *ServerInterfaceWrapper) ListCompletions(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "roomId" -------------
	var roomId string

	err = runtime.BindStyledParameterWithOptions("simple", "roomId", r.PathValue("roomId"), &roomId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "roomId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListCompletionsParams

	// ------------- Required query parameter "from" -------------

	if paramValue := r.URL.Query().Get("from"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "from", r.URL.Query(), &params.From)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		return
	}

	// ------------- Required query parameter "to" -------------

	if paramValue := r.URL.Query().Get("to"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "to", r.URL.Query(), &params.To)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		return
	}

	// ------------- Optional query parameter "questId" -------------

	err = runtime.BindQueryParameter("form", true, false, "questId", r.URL.Query(), &params.QuestId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "questId", Err: err})
		return
	}

	// ------------- Optional query parameter "memberId" -------------

	err = runtime.BindQueryParameter("form", true, false, "memberId", r.URL.Query(), &params.MemberId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "memberId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCompletions(w, r, roomId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRoomDailyStatus operation middleware
func (siw *ServerInterfaceWrapper) GetRoomDailyStatus(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "roomId" -------------
	var roomId string

	err = runtime.BindStyledParameterWithOptions("simple", "roomId", r.PathValue("roomId"), &roomId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "roomId", Err: err})
		return
	}

	// ------------- Path parameter "date" -------------
	var date openapi_types.Date

	err = runtime.BindStyledParameterWithOptions("simple", "date", r.PathValue("date"), &date, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "date", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRoomDailyStatus(w, r, roomId, date)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RotateInviteToken operation middleware
func (siw *ServerInterfaceWrapper) RotateInviteToken(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "roomId" -------------
	var roomId string

	err = runtime.BindStyledParameterWithOptions("simple", "roomId", r.PathValue("roomId"), &roomId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "roomId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RotateInviteToken(w, r, roomId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// KickRoomMember operation middleware
func (siw *ServerInterfaceWrapper) KickRoomMember(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "roomId" -------------
	var roomId string

	err = runtime.BindStyledParameterWithOptions("simple", "roomId", r.PathValue("roomId"), &roomId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "roomId", Err: err})
		return
	}

	// ------------- Path parameter "memberId" -------------
	var memberId string

	err = runtime.BindStyledParameterWithOptions("simple", "memberId", r.PathValue("memberId"), &memberId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "memberId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.KickRoomMember(w, r, roomId, memberId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRecurringQuests operation middleware
func (siw *ServerInterfaceWrapper) ListRecurringQuests(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "roomId" -------------
	var roomId string

	err = runtime.BindStyledParameterWithOptions("simple", "roomId", r.PathValue("roomId"), &roomId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "roomId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRecurringQuests(w, r, roomId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateRecurringQuest operation middleware
func (siw *ServerInterfaceWrapper) CreateRecurringQuest(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "roomId" -------------
	var roomId string

	err = runtime.BindStyledParameterWithOptions("simple", "roomId", r.PathValue("roomId"), &roomId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "roomId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateRecurringQuest(w, r, roomId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateRecurringQuest operation middleware
func (siw *ServerInterfaceWrapper) UpdateRecurringQuest(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "roomId" -------------
	var roomId string

	err = runtime.BindStyledParameterWithOptions("simple", "roomId", r.PathValue("roomId"), &roomId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "roomId", Err: err})
		return
	}

	// ------------- Path parameter "questId" -------------
	var questId string

	err = runtime.BindStyledParameterWithOptions("simple", "questId", r.PathValue("questId"), &questId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "questId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateRecurringQuest(w, r, roomId, questId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteMyQuestCompletion operation middleware
func (siw *ServerInterfaceWrapper) DeleteMyQuestCompletion(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "roomId" -------------
	var roomId string

	err = runtime.BindStyledParameterWithOptions("simple", "roomId", r.PathValue("roomId"), &roomId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "roomId", Err: err})
		return
	}

	// ------------- Path parameter "questId" -------------
	var questId string

	err = runtime.BindStyledParameterWithOptions("simple", "questId", r.PathValue("questId"), &questId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "questId", Err: err})
		return
	}

	// ------------- Path parameter "date" -------------
	var date openapi_types.Date

	err = runtime.BindStyledParameterWithOptions("simple", "date", r.PathValue("date"), &date, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "date", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteMyQuestCompletion(w, r, roomId, questId, date)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutMyQuestCompletion operation middleware
func (siw *ServerInterfaceWrapper) PutMyQuestCompletion(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "roomId" -------------
	var roomId string

	err = runtime.BindStyledParameterWithOptions("simple", "roomId", r.PathValue("roomId"), &roomId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "roomId", Err: err})
		return
	}

	// ------------- Path parameter "questId" -------------
	var questId string

	err = runtime.BindStyledParameterWithOptions("simple", "questId", r.PathValue("questId"), &questId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "questId", Err: err})
		return
	}

	// ------------- Path parameter "date" -------------
	var date openapi_types.Date

	err = runtime.BindStyledParameterWithOptions("simple", "date", r.PathValue("date"), &date, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "date", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutMyQuestCompletion(w, r, roomId, questId, date)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/healthz", wrapper.GetHealth)
	m.HandleFunc("GET "+options.BaseURL+"/v1/invites/{inviteToken}", wrapper.GetInviteSummary)
	m.HandleFunc("POST "+options.BaseURL+"/v1/invites/{inviteToken}/members", wrapper.JoinInviteAsMember)
	m.HandleFunc("GET "+options.BaseURL+"/v1/rooms", wrapper.ListRooms)
	m.HandleFunc("POST "+options.BaseURL+"/v1/rooms", wrapper.CreateRoom)
	m.HandleFunc("GET "+options.BaseURL+"/v1/rooms/{roomId}", wrapper.GetRoomDashboard)
	m.HandleFunc("PATCH "+options.BaseURL+"/v1/rooms/{roomId}", wrapper.UpdateRoom)
	m.HandleFunc("GET "+options.BaseURL+"/v1/rooms/{roomId}/completions", wrapper.ListCompletions)
	m.HandleFunc("GET "+options.BaseURL+"/v1/rooms/{roomId}/daily-status/{date}", wrapper.GetRoomDailyStatus)
	m.HandleFunc("POST "+options.BaseURL+"/v1/rooms/{roomId}/invite-token:rotate", wrapper.RotateInviteToken)
	m.HandleFunc("DELETE "+options.BaseURL+"/v1/rooms/{roomId}/members/{memberId}", wrapper.KickRoomMember)
	m.HandleFunc("GET "+options.BaseURL+"/v1/rooms/{roomId}/recurring-quests", wrapper.ListRecurringQuests)
	m.HandleFunc("POST "+options.BaseURL+"/v1/rooms/{roomId}/recurring-quests", wrapper.CreateRecurringQuest)
	m.HandleFunc("PATCH "+options.BaseURL+"/v1/rooms/{roomId}/recurring-quests/{questId}", wrapper.UpdateRecurringQuest)
	m.HandleFunc("DELETE "+options.BaseURL+"/v1/rooms/{roomId}/recurring-quests/{questId}/completions/{date}", wrapper.DeleteMyQuestCompletion)
	m.HandleFunc("PUT "+options.BaseURL+"/v1/rooms/{roomId}/recurring-quests/{questId}/completions/{date}", wrapper.PutMyQuestCompletion)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xdfVMbR5r/Kl1zV3W7VWNpJDAGVd0f2F6/Bi8vzl6ygXI1UgtNkGbkmRYJS1EFsZIj",
	"wF28FYiFI1zkljVmi6tVQM6SCnX/3LfRtL7DVveMRvPSI42QUHDCf0Iz0/3007/n7ff0iCUhqebyqoIU",
	"rAuJJUFPZlAOso+31Fw+i7CsKvSvvKbmkYZlxK4lzWsoNYrpn+hTSP8WEkJcig9dkwauxaXHsXgiJiUk",
	"6Y+CKKRVLQexkBBSEKNrWM4hQRTwYp4+omNNVuaEZZFdDBrOOwjv+RzKzSLtfso9Rg7lnkixexNDozev",
	"3x38cGhsYGTyg+EPRu4MTAxO3OGNo6imHCmkJzU5b6pA+D37ALPAnAbQu0Ba1QDOIJC0lRURRMfk5Idy",
	"7R9ngOwVyYvngOwUjb9s1r9ZI99UycstQRSUQjYLZ+mtWCsgjixPC0jH3iWxL81F3Rz+8IE0Pjw5NPEw",
	"fmfoUezejVuDY7xFaaqa845Dv7N0c+PB4AfxB48f3r7+x6EPR8aGJ+J3Bv3D0HHQ04KsoZSQ+MgWzh5d",
	"bOyNvRWiCysz9ojq7McoialgTZzdhhgGYs3C4b9qKC0khH+JNnEbtUAbdSDWK6ljkNYyvCfrmC+HjFHO",
	"/SGsLPaEUNPgok82c7z2Yk0iPa8qOvKLlrIEDieQvUSvIGyY1nL0SoYO59cQxGgSJQsaxeEEhd0kYujj",
	"COK0Wifa69sl4y9vgPHVDtleA8bRGYgbr4/qxQogu1XybBUYB2tko1w72QPkuFpfPapvl2qnFZ4x6aqG",
	"f6+lkNbCTaRkPZ+Fi0Cl90XA/TRQczLGKCUyj6EjbQFpAObzSEnpAKvsW6SkXA5EEoWcrMi5Qo59tgSR",
	"FYzmkMaQJeOsx2k6V2YtibcKj/LNgUTXalrsharmAsxEWZAxel/LuoXKYJzXE9EozOcj1reRpJqLfqzK",
	"SlRewE8k/f2Ju0/H743MD6Wlibu5D+eHF51Ov6DJwT6/HfDGzLssN9jubro4tstI10O4nSnrNq9G2VS2",
	"hM3hRIeOWms4EONpWYHZuyr0KDkmSWT3zEb4wT79i7ysGl/tALJ7Sl7vBkPaHvI25EW/O/QywFCbQxhQ",
	"J2+HPrpMd9Azo/bQtYFQUTuLYAppj+TkvAJzHiiTjXL92zWqRPjpe0iZwxkhER8MiG6PfI9b+jA1YFQO",
	"edPTZORPqsJZ8v3RR6OgcRnIKaRgOS0jrcXKR3UZRqeQWsi2tTdbYp8GHHshePfFIW876HTlqN1GHtpR",
	"34ZydpEKO4UhLvjdsXkDmFNhFujsFpCE2WQhCzFKgdlFh2eMTCuPMwhY3g80pndkWiCpFhQMZB1oakFJ",
	"oRRIa2puWvkNTGJ5AQGtES8AsyLr9v9/AVINKW8VsJpOjyMtiRQMoiAmSb+NTFMLRQr1uB8JdFztiQl7",
	"QRSo4E9y7GMeaWm66hkOpn6naarGy2RSHoAq1p4/wXAeKXz/putwzvPY4wzEoPEsVQDMagimFkFBRykg",
	"KwBnmFZMeLbGIROqOQ9vV9lyggGFGqtthShTJd7JzUd5c95DMIsz/BCj2+BqqkSdb7tS67Hg2bqzGYfE",
	"oe3lPgsEU4VcDmqL/MVqrqwnfALqzpb8SWgnoZAf2LyStV1gd/r16yq0mh+osmI+biYCfE2/g6lEmMUG",
	"JhEKN+Qafz8jByttQ65HQHuscBJ1gwPuZoaGwpi9yZ60NZA1GLk7cjsefxS7cS/+aGDi3o2p2M27PE9N",
	"M9mWhIg0nBjojBBRuk2KrNLACmZmntHE0YwzdbEv9oU5kF2kgdJMfZjMDmUG7yFLJZp5RgBBxXzTLRr5",
	"XQu43q6uuixcVENp511HM1a2silv3kajhYphdpRlUgFzx9oUp54td1BCltIs2UTubnGXHiQWDyXjBezk",
	"LWwnCFMp2SzRxx2QScOsjkSvh1S9IGjH5zlNclhqy+8tc+T2BG4/tFlu3s7RxDpyNNaYNxfH2sA2rDPs",
	"Bwkj94AVlXUTS66RXFs1q6pZBJWeOUIPedQPpkcUCvlUjzHT0p/zuCSHrp0q4GFPdGDcKftMW2sJk0J3",
	"mjh7UzH35fYy9YpRbpfQh2aV/eJ1l5AFLDd0SubldXsnS4dyWPn8edxtp40uHgHhZ0usC3AOgSS7k1FP",
	"SVXR5RRizAa0ulH/ppushkmtQB3kEI5MK7dRGhayjCO5LkWmlWkWCJ08Ckq52BHZS8gwakVW5npAq0wr",
	"vzPVlwByGuAM0hCAGgIDgD+yDqCSMrtr5uLZKsRpBWeQAgbolFLkOvh3EItct2+1mnO5ApPMXCKAGGQR",
	"1DGIWyNbJI+dRUkscpvONyY5XXGM54ovA/2KMxDbLCRVzSeqNk91h9VPoJbqhpGVu49xJsP9WJ1Hnvjf",
	"guoPYIZ7lZKYyPCnsYPtdlvpF6/M2DusNi0QIJjMsA227XuW2iPUFsPzzmGjv9Rl9A/BXQf4PYey3Mjx",
	"QcC9ix3lCYzLtivGdq3m3jR6e1VGmjKj8EL5K2Qe/3ehzGKvGQPvCQOv9KJr93yaC4GJLjMPDsA6Sj1u",
	"Qz0zq0ItFYDNgqYhBY91SFKaaugUOf2HS1giFaspuHir53bKhuWH3sf0EvO/GDmTI9ZmscJvw3/xom5Y",
	"U2cijF2YvfMZ5ea6RQ/CmtDh2ZpvG/jyt8V6L2zOaTYdWhy3WuyqLRI0V3AVSB/rwJoadtBuc/WWonSv",
	"93PUeV23pTtvSE+qGGJ0v5lTtDq0EpCuDs0+HMqPxnITqYE/fPowrt0a0f8jOOft/ORLwPitT754MzBX",
	"1tT6fIlPJ91uCk/FoXdoqtkZ87SVP83LGtI5WeuNcxfesq4XelzLW604DnZ0pD8Zmn9wLz00Ls3dyDwY",
	"evjBwuTA0/hY7JP3RmD7drVzYIfookMzPIW+z/LgwMNyOVlx8t4xsYvjc5Hr5+ZuO+Fd+YRp7LyEqS11",
	"68NxQYp1n8tqq86QVI/jYIzFduRt8udnPgrT0N7QBbIk9Z21+vpp5yyJ14hvXBuIhUm2Wp4XM4Xh1vV+",
	"XDAXkCxoMl6coh7R3PZZBDWkjRZwpvnXnYZQU27LZo6UQZ7d1pyURg5heZmFlrTqx0z95Sb59nmtskJe",
	"fQ7Iiy/IbhWQz47Iy0Nqq+tboHby1vhqBxh/O6z/uRw1KiXj5C2or5TI+j7TdrFs/Fgk6/tktwTG/jAO",
	"RsfvA3rtv3ci00qtsgqMyiHZXQHkbZn8z+fWOGTH8wUwPtsjB2Xjr2eAynKwYhxWRGAc7hvHRePrfTpA",
	"fbtqbPxo3Vj7cZMc0O/e1H4qAWPjyHhdMTb2GUNIl1Df3CS7Z2S3CIyNN4xnOSiSDSYk+fY5OS7/ZkpW",
	"5rIITKkFLYmAmgaPtQLO/JaUz4zvyrYKyuagdj8iITBfCKgF06UKorCANDP4CFIkFpEoMtQ8UmBeFhLC",
	"QESKDAiikIc4wzY1mmFHfP5EP88hZsTU1CHdDlruCncRNk8BsZzZDKrsybgkmfyCgi3rh/l8Vk6yR6Mf",
	"66avNSNquHNGdsxm+HDjgu7rcRGQvW3ybNVEqHlqhmLmxRFZ37f8M1UNnNNptLHknqF3RxdiUTOF0KNL",
	"jsxiudXCXcdzmNY0mEOY1Z4f0QxLSDBNNpiihCdnaYY+Mww0leE1wZkLVC7/vBJPx9U1Y3MFGAer9dUj",
	"QL6r1F9uAlL8vnbylqJoUBrsmUzu43ftZKFmSCr/R82HrJVMt7DpAYFH+L1t46RqrcEBCVMXehtMRB0M",
	"Q17VOeBoHtgZ1e3i8oLhwcLcTTW12LNdCDpWtezO26h0yz6Axi5QjGBcmC4YkGe7pPi9C5xSH8H5qmT8",
	"7SfjeRmQl1vk+H8vpXVQkUb6J5Kx8aVR3CevioDs/5nGZOPr7wH54dD4qqWlsuD2tkyqa4BUTmuVFY6x",
	"Nk5HOczWJhgs1+0FyRbZPQX1nS3jsEpePCfFMjBOquTFEdkvsoMux1WaB9Bgb3y3yzT3tkw29mxcrZUb",
	"gZd5ECvwCqLHDTDagYlygf7bx2/wtG8vxuu3XaqvnbytVcrAd7dD6eZyZpZF2/P5ZhKB8frI+K8tKx8S",
	"Aamu1U4rgBRPyeclpk2mRktr3IwrOG86olkezZLKRYbs3ZLx99OgDWge6hcuxkX6X1zps3PkvP7A3//a",
	"yZl7Xy6lk+yjR+I6Hwp9Uy8czDudS3TJ7M4sB3qZeqlIXh1Z9R1dp6X22mmF7K9Y/oNhv+SuWli1Udo3",
	"1kvUYde/+RKQZ6v1Z6zaaO1v7iLs4odDJR12l+lypKN8rjzIp22ukI2ycVI1vi7zMtJYH+HE9hmQjf36",
	"5htz9oH+zV77gYLCFdz7mG8wFBeDcnCLKmD4c5IEH81QILltj7Oh/OADcTLjz7ubfNWFQr/3ccRPtIWK",
	"I701u3bWRtZKZG/7cgWMX42FW7H7l2LoZLdqvKa5oTvrKz2n6R0vFbTQFzYsRz0HW7gcDk2b3R3dC/EZ",
	"ojXQ0wJiPJE1Ulqz01L+OG0o3aBxsXoRozZ/+KLjhTpeg/h5coqAH5Xg2Th7vYHmaJxa6crhXaU0HXo6",
	"03UZx1u0XD0pAh6+HC7N6YyCHBvrX10zXySKLlEjDq5BrPKivv4jDdyWNGYBAny9EbPkp3WiS0q6fqsA",
	"D1l9NI/kXLBDdQ9kn5I7r+e7+LLGf/COBz2zt3RSBGY1Smu/q+LmHfcELhOkNunbW19mI4ZyB2bP4BpW",
	"55GS0NjBlOC+hO/gyrvJEAQd5gmmwutf7NVXK4C8OjIq5drpl79OQ/oF1RCefl5jXzlG5OvpeQzIauZF",
	"lxpp6rIZR7OIdzTWVGGtstKg7sjumVEpNXr/7EDAdv0/q3Yv3tI5efWcbOzRquezEjA29o2/nlp0LDu1",
	"YD2z19CH3cd32+9DOTlP19VBT7Fn4dWRxXfjBwZ5/RiTGGVKuLLMMjvU8uKL2vcVChY/Nta3GE/2bPXn",
	"sN1Gjd4EfC9oPycCHDbMb+w1bdc+5HXtqX1CP7DSn/Qd6X73Ql/we6zc3eJm+Fe55DvPn7XaV2cI9P5c",
	"kaNty22Uut9bebco9Fa/mNnnpmzA691hTPQyNmWv8uNfgI/wd7V9ziFcjI0uWVQwy5NbN+L64k/46arj",
	"h5ovSXPv/J5JuhSe6ar7d+WZGtm/DYueFABcpPXUVTnbgQ7SvFnlu93Xbfb92KL1e1v2a7SX3oP1jRnn",
	"lPGe3sY/3pAvroqMn8dMRWdxYPXUvT2drltbVcDb8cBulijkC5zKY7yAr+zsghMQ7u8C9jnz4PxDheD+",
	"OzkuGa+PrnKNX6f3upAk47Oqv+PtQltwG57Noy00fJFb3vfUJMxaP+AuiEJBy1qvMSai0Sy9llF1nBiW",
	"hiWBSmRNsdRwGdZLaNShWN+YfQvHF40GhuOrBi/qfMyTIzkuOZezPLP8zwAAAP//7XwN9QFpAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
