//go:build go1.22

// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// 헬스 체크
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// 초대 링크 정보 조회
	// (GET /v1/invites/{inviteToken})
	GetInviteSummary(w http.ResponseWriter, r *http.Request, inviteToken string)
	// 초대 링크로 최초 참가
	// (POST /v1/invites/{inviteToken}/members)
	JoinInviteAsMember(w http.ResponseWriter, r *http.Request, inviteToken string)
	// 공개 방 목록 조회
	// (GET /v1/rooms)
	ListRooms(w http.ResponseWriter, r *http.Request)
	// 방 생성
	// (POST /v1/rooms)
	CreateRoom(w http.ResponseWriter, r *http.Request)
	// 방 대시보드 조회
	// (GET /v1/rooms/{roomId})
	GetRoomDashboard(w http.ResponseWriter, r *http.Request, roomId string)
	// 방 이름, 최종 목표, 최종 목표 날짜, 커트라인, 공개 여부 수정
	// (PATCH /v1/rooms/{roomId})
	UpdateRoom(w http.ResponseWriter, r *http.Request, roomId string)
	// 날짜 범위별 완료 기록 조회
	// (GET /v1/rooms/{roomId}/completions)
	ListCompletions(w http.ResponseWriter, r *http.Request, roomId string, params ListCompletionsParams)
	// 특정 날짜의 방 상태 조회
	// (GET /v1/rooms/{roomId}/daily-status/{date})
	GetRoomDailyStatus(w http.ResponseWriter, r *http.Request, roomId string, date openapi_types.Date)
	// 초대 링크 재발급
	// (POST /v1/rooms/{roomId}/invite-token:rotate)
	RotateInviteToken(w http.ResponseWriter, r *http.Request, roomId string)
	// 방 멤버 강퇴
	// (DELETE /v1/rooms/{roomId}/members/{memberId})
	KickRoomMember(w http.ResponseWriter, r *http.Request, roomId string, memberId string)
	// 반복 퀘스트 목록 조회
	// (GET /v1/rooms/{roomId}/recurring-quests)
	ListRecurringQuests(w http.ResponseWriter, r *http.Request, roomId string)
	// 반복 퀘스트 생성
	// (POST /v1/rooms/{roomId}/recurring-quests)
	CreateRecurringQuest(w http.ResponseWriter, r *http.Request, roomId string)
	// 반복 퀘스트 삭제
	// (DELETE /v1/rooms/{roomId}/recurring-quests/{questId})
	DeleteRecurringQuest(w http.ResponseWriter, r *http.Request, roomId string, questId string)
	// 반복 퀘스트 수정
	// (PATCH /v1/rooms/{roomId}/recurring-quests/{questId})
	UpdateRecurringQuest(w http.ResponseWriter, r *http.Request, roomId string, questId string)
	// 내 완료 기록 취소
	// (DELETE /v1/rooms/{roomId}/recurring-quests/{questId}/completions/{date})
	DeleteMyQuestCompletion(w http.ResponseWriter, r *http.Request, roomId string, questId string, date openapi_types.Date)
	// 내 반복 퀘스트 완료 처리
	// (PUT /v1/rooms/{roomId}/recurring-quests/{questId}/completions/{date})
	PutMyQuestCompletion(w http.ResponseWriter, r *http.Request, roomId string, questId string, date openapi_types.Date)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetInviteSummary operation middleware
func (siw *ServerInterfaceWrapper) GetInviteSummary(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "inviteToken" -------------
	var inviteToken string

	err = runtime.BindStyledParameterWithOptions("simple", "inviteToken", r.PathValue("inviteToken"), &inviteToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "inviteToken", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetInviteSummary(w, r, inviteToken)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// JoinInviteAsMember operation middleware
func (siw *ServerInterfaceWrapper) JoinInviteAsMember(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "inviteToken" -------------
	var inviteToken string

	err = runtime.BindStyledParameterWithOptions("simple", "inviteToken", r.PathValue("inviteToken"), &inviteToken, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "inviteToken", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.JoinInviteAsMember(w, r, inviteToken)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRooms operation middleware
func (siw *ServerInterfaceWrapper) ListRooms(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRooms(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateRoom operation middleware
func (siw *ServerInterfaceWrapper) CreateRoom(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateRoom(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRoomDashboard operation middleware
func (siw *ServerInterfaceWrapper) GetRoomDashboard(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "roomId" -------------
	var roomId string

	err = runtime.BindStyledParameterWithOptions("simple", "roomId", r.PathValue("roomId"), &roomId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "roomId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRoomDashboard(w, r, roomId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateRoom operation middleware
func (siw *ServerInterfaceWrapper) UpdateRoom(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "roomId" -------------
	var roomId string

	err = runtime.BindStyledParameterWithOptions("simple", "roomId", r.PathValue("roomId"), &roomId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "roomId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateRoom(w, r, roomId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListCompletions operation middleware
func (siw *ServerInterfaceWrapper) ListCompletions(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "roomId" -------------
	var roomId string

	err = runtime.BindStyledParameterWithOptions("simple", "roomId", r.PathValue("roomId"), &roomId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "roomId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListCompletionsParams

	// ------------- Required query parameter "from" -------------

	if paramValue := r.URL.Query().Get("from"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "from", r.URL.Query(), &params.From)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		return
	}

	// ------------- Required query parameter "to" -------------

	if paramValue := r.URL.Query().Get("to"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "to", r.URL.Query(), &params.To)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		return
	}

	// ------------- Optional query parameter "questId" -------------

	err = runtime.BindQueryParameter("form", true, false, "questId", r.URL.Query(), &params.QuestId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "questId", Err: err})
		return
	}

	// ------------- Optional query parameter "memberId" -------------

	err = runtime.BindQueryParameter("form", true, false, "memberId", r.URL.Query(), &params.MemberId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "memberId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListCompletions(w, r, roomId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetRoomDailyStatus operation middleware
func (siw *ServerInterfaceWrapper) GetRoomDailyStatus(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "roomId" -------------
	var roomId string

	err = runtime.BindStyledParameterWithOptions("simple", "roomId", r.PathValue("roomId"), &roomId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "roomId", Err: err})
		return
	}

	// ------------- Path parameter "date" -------------
	var date openapi_types.Date

	err = runtime.BindStyledParameterWithOptions("simple", "date", r.PathValue("date"), &date, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "date", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetRoomDailyStatus(w, r, roomId, date)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RotateInviteToken operation middleware
func (siw *ServerInterfaceWrapper) RotateInviteToken(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "roomId" -------------
	var roomId string

	err = runtime.BindStyledParameterWithOptions("simple", "roomId", r.PathValue("roomId"), &roomId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "roomId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RotateInviteToken(w, r, roomId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// KickRoomMember operation middleware
func (siw *ServerInterfaceWrapper) KickRoomMember(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "roomId" -------------
	var roomId string

	err = runtime.BindStyledParameterWithOptions("simple", "roomId", r.PathValue("roomId"), &roomId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "roomId", Err: err})
		return
	}

	// ------------- Path parameter "memberId" -------------
	var memberId string

	err = runtime.BindStyledParameterWithOptions("simple", "memberId", r.PathValue("memberId"), &memberId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "memberId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.KickRoomMember(w, r, roomId, memberId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListRecurringQuests operation middleware
func (siw *ServerInterfaceWrapper) ListRecurringQuests(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "roomId" -------------
	var roomId string

	err = runtime.BindStyledParameterWithOptions("simple", "roomId", r.PathValue("roomId"), &roomId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "roomId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListRecurringQuests(w, r, roomId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateRecurringQuest operation middleware
func (siw *ServerInterfaceWrapper) CreateRecurringQuest(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "roomId" -------------
	var roomId string

	err = runtime.BindStyledParameterWithOptions("simple", "roomId", r.PathValue("roomId"), &roomId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "roomId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateRecurringQuest(w, r, roomId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteRecurringQuest operation middleware
func (siw *ServerInterfaceWrapper) DeleteRecurringQuest(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "roomId" -------------
	var roomId string

	err = runtime.BindStyledParameterWithOptions("simple", "roomId", r.PathValue("roomId"), &roomId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "roomId", Err: err})
		return
	}

	// ------------- Path parameter "questId" -------------
	var questId string

	err = runtime.BindStyledParameterWithOptions("simple", "questId", r.PathValue("questId"), &questId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "questId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteRecurringQuest(w, r, roomId, questId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateRecurringQuest operation middleware
func (siw *ServerInterfaceWrapper) UpdateRecurringQuest(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "roomId" -------------
	var roomId string

	err = runtime.BindStyledParameterWithOptions("simple", "roomId", r.PathValue("roomId"), &roomId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "roomId", Err: err})
		return
	}

	// ------------- Path parameter "questId" -------------
	var questId string

	err = runtime.BindStyledParameterWithOptions("simple", "questId", r.PathValue("questId"), &questId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "questId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateRecurringQuest(w, r, roomId, questId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteMyQuestCompletion operation middleware
func (siw *ServerInterfaceWrapper) DeleteMyQuestCompletion(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "roomId" -------------
	var roomId string

	err = runtime.BindStyledParameterWithOptions("simple", "roomId", r.PathValue("roomId"), &roomId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "roomId", Err: err})
		return
	}

	// ------------- Path parameter "questId" -------------
	var questId string

	err = runtime.BindStyledParameterWithOptions("simple", "questId", r.PathValue("questId"), &questId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "questId", Err: err})
		return
	}

	// ------------- Path parameter "date" -------------
	var date openapi_types.Date

	err = runtime.BindStyledParameterWithOptions("simple", "date", r.PathValue("date"), &date, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "date", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteMyQuestCompletion(w, r, roomId, questId, date)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PutMyQuestCompletion operation middleware
func (siw *ServerInterfaceWrapper) PutMyQuestCompletion(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "roomId" -------------
	var roomId string

	err = runtime.BindStyledParameterWithOptions("simple", "roomId", r.PathValue("roomId"), &roomId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "roomId", Err: err})
		return
	}

	// ------------- Path parameter "questId" -------------
	var questId string

	err = runtime.BindStyledParameterWithOptions("simple", "questId", r.PathValue("questId"), &questId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "questId", Err: err})
		return
	}

	// ------------- Path parameter "date" -------------
	var date openapi_types.Date

	err = runtime.BindStyledParameterWithOptions("simple", "date", r.PathValue("date"), &date, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "date", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PutMyQuestCompletion(w, r, roomId, questId, date)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of http.ServeMux.
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	ServeHTTP(w http.ResponseWriter, r *http.Request)
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc("GET "+options.BaseURL+"/healthz", wrapper.GetHealth)
	m.HandleFunc("GET "+options.BaseURL+"/v1/invites/{inviteToken}", wrapper.GetInviteSummary)
	m.HandleFunc("POST "+options.BaseURL+"/v1/invites/{inviteToken}/members", wrapper.JoinInviteAsMember)
	m.HandleFunc("GET "+options.BaseURL+"/v1/rooms", wrapper.ListRooms)
	m.HandleFunc("POST "+options.BaseURL+"/v1/rooms", wrapper.CreateRoom)
	m.HandleFunc("GET "+options.BaseURL+"/v1/rooms/{roomId}", wrapper.GetRoomDashboard)
	m.HandleFunc("PATCH "+options.BaseURL+"/v1/rooms/{roomId}", wrapper.UpdateRoom)
	m.HandleFunc("GET "+options.BaseURL+"/v1/rooms/{roomId}/completions", wrapper.ListCompletions)
	m.HandleFunc("GET "+options.BaseURL+"/v1/rooms/{roomId}/daily-status/{date}", wrapper.GetRoomDailyStatus)
	m.HandleFunc("POST "+options.BaseURL+"/v1/rooms/{roomId}/invite-token:rotate", wrapper.RotateInviteToken)
	m.HandleFunc("DELETE "+options.BaseURL+"/v1/rooms/{roomId}/members/{memberId}", wrapper.KickRoomMember)
	m.HandleFunc("GET "+options.BaseURL+"/v1/rooms/{roomId}/recurring-quests", wrapper.ListRecurringQuests)
	m.HandleFunc("POST "+options.BaseURL+"/v1/rooms/{roomId}/recurring-quests", wrapper.CreateRecurringQuest)
	m.HandleFunc("DELETE "+options.BaseURL+"/v1/rooms/{roomId}/recurring-quests/{questId}", wrapper.DeleteRecurringQuest)
	m.HandleFunc("PATCH "+options.BaseURL+"/v1/rooms/{roomId}/recurring-quests/{questId}", wrapper.UpdateRecurringQuest)
	m.HandleFunc("DELETE "+options.BaseURL+"/v1/rooms/{roomId}/recurring-quests/{questId}/completions/{date}", wrapper.DeleteMyQuestCompletion)
	m.HandleFunc("PUT "+options.BaseURL+"/v1/rooms/{roomId}/recurring-quests/{questId}/completions/{date}", wrapper.PutMyQuestCompletion)

	return m
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xdfU8bV7r/Kkdzr3R3pQm2gZCAtH+QZPNashDS3nYLigb7GE+xZ5yZY1o2QoLEzaXA",
	"3lAViklt5OyyIVSs6gSnS1V0/7nfxnP8HVbnxeN5OeOX2Lik5T9sz5x5zvP6O7/nsXkkRfVUWteghkxp",
	"5JFkRhMwpdA/r+qpdBIiVdfIq7Shp6GBVEg/i7LPYGwUkZfwC4W8lkak/nD/0IXwwIX+8P1I/0gkPBIO",
	"/1mSpbhupBQkjUgxBcELSE1BSZbQQprcYiJD1WalRZl+GLScdxHR/SmYmoHGrZh7jRRMPQhHbk4MjV65",
	"eGPwk6GxgeF7H1/+ePj6wMTgxHXROprO5IhBM2qoaaYC6U/0DyUJ2GMAuQrEdQOgBARRW1l9kux4OP4x",
	"X/nXCcDFLN7eAHgna/19vfrtCv62jJ9vSrKkZZJJZYZciowMFMjyMANN5N0SfZNt6srlT26Hxy/fG5q4",
	"03996G7k5qWrg2OiTRm6nvKuQ97jurl0e/Dj/tv371y7+OehT4bHLk/0Xx/0L0PWgQ8zqgFj0sintnD2",
	"6nLNNrYpZJevTNsr6jOfwSgigtX97JqClEBf4374nwaMSyPSf4TqfhviThtyeKxXUscijWX4QDWRWA4V",
	"wZT7j1ZlsR+oGIay4JONrddcrHvQTOuaCf2ixbjArQlkb9ErCF2msRzdkqHN5xtQQfAejGYM4ocTxO3u",
	"Qep9AkGcUev09upWzvr7K2A928FbK8A6PAH91svDarYEcKGMnywDa38Fr+UrR0WA35Sry4fVrVzluCQK",
	"JlM30J+MGDQapImYaqaTygLQyXV94FYc6CkVIRiTacYwoTEPDaCk01CLmQDp9F2oxVwJJCxLKVVTU5kU",
	"/ZsLomoIzkKDepaKkp6k6dwZ35JoFx7ls4Vk124a2ELXUwFhos2rCH5oJN1CJRBKmyOhkJJO9/F3+6J6",
	"KvSZrmohdR49CJsfTtx4OH5zeG4oHp64kfpk7vKCM+lnDDU45zdzvDF2FU+Dza4mm6NWhqbZQtqZ5Jd5",
	"NUofZUtYX0526KixhgN9PK5qSvKGrniUHAmHceHE9vD9PfIKPy9bz3YALhzjl4Vgl7aXvKaIqt918jFA",
	"ijELESBJ3i59ZJvuoseq9tCFgZaqdhIqMWjcVaNzmpLyuDJey1e/WyFKVL74AGqzKCGN9A8GVLe7vtu5",
	"PpgGrNKB6PEEjPxF1wRbvjV6dxTUPgZqDGpIjavQaLDzUVNVQpNQzyRFj5pXTXVGTapooRUP/Kh+tciz",
	"6G592nPYUfLa1CWAY+PNfLCjjO/OFi1n/GuKmlwgkk8iBWX8eZ1dAGZ1JQlMegmIKsloJqkgGAMzC44U",
	"2zel3U9AwNMoqD3eAdlAVM9oCKgmMPSMFoMxEDf01JT2OyWK1HkIjFrhATQc+eX/vw1iNSmvZpAej49D",
	"Iwo1BEIgEg7/vm+KhDrUSOr+VCLrGg9Y/EiyRAR/kKJ/pqERJ7ueFnjMHw1DN0SQKObxdI07wAOkzEFN",
	"nChNU5n13HY/oSBQu5coQEkaUIktgIwJY0DVAEpQrTA/b1xAqFD154isSrcT7FCwtttGHsVU4n04u1X0",
	"zJtQSaKEuFaZtnPVVaLPNd0pvy34aZ3FjEPiluPlFq0ok5lUSjEWxJs1XPCpdSTrhl1+NNtOTRVXSK9k",
	"TTfYmX79umpZzbd1VWO3M0Qh1vR7iEla2WwgGtGEtdv64QTvLzWt3R4B7bVak6gTPxAas2VXGLON7MG/",
	"gfTD8I3ha/39dyOXbvbfHZi4eWkycuWGKFMTSNyQWQlfHhloj1nROkVX/IzBixkDHXU/mnZiIPvDnlAQ",
	"qot90Oo4iMrsUGawDSmUqOOMAKaL5qarpPK7NnCx2QHtrJBaNaW96z7qtbJRTHlxG6kWOlKSoxRJBTw7",
	"0uSU6zG5g1viSuOyyUJrCbceJJbIS8YzyEmA2ElQicVUdtYfd7hMXEmaUPZmSN3rBM2IQWdIXg43JQoX",
	"BXJ7CrfftSk2b5ZoIm0lGr7mlYWxJm7bajLsBZujdoFeVU3mS66VXKaa0fUkVLSuJUIPC9ULykiWMulY",
	"l32mYT4XkVIOXTtVIPI92eHjTtmnm0ZLKxC6XeDshWLuj5vL1C1quhmgb5me9ovXGSAL2G7LkMxLEHdP",
	"ljbl4Hj+XdJtux0zEQHhZ0v4B8osBFF6JeWworpmqjFImQ2Ft7X+y2SsBqNWFBOkIOqb0q7BuJJJUo7k",
	"YrhvSpuihdDJo8CYix1RvYQMpVZUbbYLtMqU9kemvhGgxgFKQAMCxYBgAIhXNoGixVibjm2e7kKe0lAC",
	"amCAPDLcdxH8AUT6LtqX8i5fKkMlY1sECgJJqJgI9POVOcljo6gwrdws+UbCzlQcEaXis8DjooSCbDqT",
	"qOZz3ZgjukP654oR64TaVTuvcYwqv6/PQU/9b9AzCKCYuwVJmGf4YexgM2trvSKoKXuH9HoEAqhEE9TA",
	"dnzPkHhUjIV2COzWqn97KaxrpDhFDi2Q4AE5M4gdd7ugz5fc7tAW4KCkuH30bNb87k7ruVvnUSYzbF0o",
	"/1FbIBtbu91FhZTkqZKd3SYxxNMTpoAalV0e4bNGC37WISwSOG1buOiaYiZmdMWIBfh7xjCghsbaZFDf",
	"F8dpleVFekxZuNr12KfLinHBffIRLQ4IOpEb7QFxbFDLiSJI0Gr6oCKMnVoOEdPd9X3LHg9rHGs+M4jl",
	"b+rr3Yg5Z9i0GXHCo2xHPZugZwUfUcltbURTLQ6aGddsKErnen+HQ2jHPfP2u+UeZORg6tOZmaQalWQp",
	"bajzJABcVL39qS9M7+lIQfBWHfk0GvYJQOdDM3eG0qOR1ERs4KMv7vQbV4fN/w6G+O1PDAWs33hiyAsa",
	"Xdiu8VyOTyedmlmk4pZtPllvBHq66F+kVQOaApB+6Z1BumqamS7jft55FPiOCc0HQ3O3b8aHxsOzlxK3",
	"h+58PH9v4GH/WOTzD4aV5t1558IO0WWHZkQK/ZCi9cAhw5SqOWn+iNzB2GHfxa4MHtYbKO9K+dqCNJ4T",
	"DNKVe0StqYZaJKscoz2cr0nb9NUvPMxT097QKfI81Z2V6upx+zyPNy4vXRiItILIGo7OMWECmImOju4e",
	"n6IZIZoxVLQwSW5iLjMDFQMaoxmUqL+6XtvQpDvQ6bNoo4VeVheYFBJpcZFWmrju97fq83X83UaltIR3",
	"vwR4+ykulAF+fIifH5DQXd0ElaO31rMdYH1/UP06H7JKOevoLagu5fDqHrVUNm/9lMWre7iQA2MfjYPR",
	"8VuAfPa/O31TWqW0DKzSAS4sAfw2j//2JV8H73jeANbjIt7PW/84AUSW/SXroCQD62DPepO1vtkjC1S3",
	"ytbaT/zCyk/reJ+896rycw5Ya4fWy5K1tkf5UbKF6vo6LpzgQhZYa68oy7SfxWtUSPzdBn6T/92kqs0m",
	"IZjUM0YUAj0O7hsZlPg9zp9YL/K2CvJsUbsbMyLR1AiITclWJVmahwarRVK4L9IXJr6hp6GmpFVpRBro",
	"C/cNEASioAQ1aihBB5z+Qv6ehTQBkDShEHOQk7V0AyI2A0VBOaux9M7+cJiRIhrimUNJp5NqlN4a+sxk",
	"qZc5XWtTVnYJp/7h9gti1zdZgItb+Mky81A2M0R8ZvsQr+7xdE1Uo8yapPhwuafJ1aH5SIghCjP0yAE0",
	"Fh0b93jiZtZ6UayuHldKS6Q2WD8cg0pph5ieUQQAF79mbeMt66hcdxVaOnZXrLU966AMuCtXdzbJK2t9",
	"Ca8VgVXaJFa1SgfsnTxZ4Js8tXShbD3bqW4VAV7J8XXIGc9nFdfkFDWpoaQgoifvTwkaJJhSoXZjXKcH",
	"X9XLNOuM1i3lrTnTp2h58SiZyAHKK9b6ErD2l6vLhwC/KFWfrwOcfV05ektcfDA82DWZ3JORzWQhhsel",
	"/yOxTS1Gcta6x0M9wlOH4Xtw+CvThdnEYUMOfiWtm4KQrc9SjZr20fqU3YPW7yt6bKFrVgiaeFt0Y0wi",
	"3aLPQSOnKEawX7D6APCTAs6+djlnuIfOuZuzvv/Z2sgD/HwTv/nnmYwOItJw70Sy1r6ysnt4Nwvw3tcE",
	"MFjfvAb4xwPrWcNIpfn4bR6XVwAukTogCNba4JojbG16RVhXrINNXDjmBQFvb+BsHlhHZbx9iPeyoA7j",
	"/sAIAVYkvj+wXhSoEt/mSQGpudhKvgYQaDLhAMFXLij/QqU6xVTuI3pEhrA3403hLitUjt5WSnngu9qh",
	"f7ad6UXZToK+J8nAenlo/XWT4zYZ4PJK5bgEcPYYf5mj2qRq5FoTIsNgfHdI0ChBc/ksdfJCzvrhOMgA",
	"9a9eSKeTLf3fU+pxnhR8SUVs/8rRidsuZzJf9jA5CfMQcX2mF4HPO/NM6BFDow2AbC6Ldw/5GZbsk6u9",
	"clzCe0s8f1Dfz7lPV/RUlNuzVnMkd1e//QrgJ8vVJ/RU1Djf3IDIRZS3hD/sxtvZQKbipkFQTnOgeBE4",
	"jfTQnaidAV7bq66/Yk8f6N3TKz8Sp3DV+R5CD+rF2SA4zikN6n9OMuPTaeJI7tgTGFRcfBQUTfgheJ2T",
	"O1XX734d8ZOJLdWR7oZds2jDKzlc3DpbBeM3E+G8dv9aAh0XytZLgg2dqE8WgkAZ4J/3qqvHVuEEF45l",
	"wFEq3j60flziTtlqtQ55homE3BtB0+6O96mkEpkv9DADKZPEV4obNloVr9OEzQ5aF+mnsWr950/a3qjj",
	"Oyy/DNQI+GkRUejT76YQ6CY4Qp3nwXOk02YCpHkNWG82ySn2KAtE/uVIac5kFJTYaOvuAvsWWOgRCeLg",
	"owk/dVRXfyL1nEuD//YlkQGv5XFxg59SamcWxgbIwNf3qX3g2oDsOLDwo7vr3EKSf/W7LF88ZK8WcuZ5",
	"XChTvn5pHX9btp5lQeXopPK6BKq7K+Tqp8UaFcCu2V8CeGvVWt1sfDCqj02dclJ3L8Rz6rtn39M/cfmH",
	"I0Xuz9pzR1nADsrEyufnrvc8G7nSAMkLPtv60JXcUkpinY0LSJ+D2ohBR32Cuye+UaD3k7wIGo8KJuyr",
	"T4vV5RLAu4dWKV85/uq3GUi/ouONp+tYs6sgiHydR08A8ZZj6FENKi+yWp6EovFlpsJKaanGKuLCiVXK",
	"1cYnaKN8q/o/ZXucgesc727gtSI5kD3OAWttz/rHMWeK6eAHv6dY0we7l71dpzUpi3lcwi/KbixAmf18",
	"Ee8vWRs566AkKuN4e4ONmGTx07+C6rPD6tYra6M+c+FOFHfU6BxRYBst1q7VcceRpZOEMyhqTzFymKr1",
	"PAXk6QDS9tPK6xLxSr8TEuS3vkSHUnqfJICVox5bj6xuUJ9OD3AkC3Gfs54k7GG+Cw/tr2sE0hr3fPP9",
	"71+NDf7GtdBawhPLOWh97znERnZ11lrvD2s5WtfCZrH7S0zvVxuh0Y/E9rgxHfBDBK2E6FlsTJ8D8V9B",
	"jvB39n3JobUaG3rEee+WAblbEgoZHv8TF/M2GGcvKar44djazXEijmDj/XWAi8v4+QGD0LIQQxdyvmRY",
	"OTqpMXEBRJkAXl+jm+lNFhSDbMcvqncZY/v8ger8HG3/knFew9Lu2Oh24FNDN0MFDWcK3seAOLU5hXcH",
	"GOEzATDOBxnOE09vEo9vOqFjxOEcYXA0+uogRFTPxxb4DzzaP41w5jNYzzppAqTg6cf+6xV+es4V/DJh",
	"KjthLYtYD8HchXZ8GYgsHtiBl6V0RkAgjGfQeZydMgAR/hBtj5GH4F8BBc8M4Tc56+XhOdb4bWavUwEZ",
	"j8v+QRyXtwWPDtHnGPO1XOSW9wM9qiT5fwyRZCljJPk3x0dCoST5LKGbaORy+HJYIhLxRzyqpQz+vV+S",
	"UPg7rM/peKPW8HS8VWtvOG/zYCTHR87tLE4v/jsAAP//7lVGrrtvAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
