// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for DailyGoalStatus.
const (
	GoalMet     DailyGoalStatus = "goal_met"
	Perfect     DailyGoalStatus = "perfect"
	UnderTarget DailyGoalStatus = "under_target"
)

// Defines values for MemberRole.
const (
	MemberRoleLeader MemberRole = "leader"
	MemberRoleMember MemberRole = "member"
)

// Completion defines model for Completion.
type Completion struct {
	CompletedAt time.Time          `json:"completedAt"`
	Date        openapi_types.Date `json:"date"`
	MemberId    string             `json:"memberId"`

	// Note Optional member note for the completion.
	Note    *string `json:"note"`
	QuestId string  `json:"questId"`
	RoomId  string  `json:"roomId"`
}

// CompletionData defines model for CompletionData.
type CompletionData struct {
	Completion Completion `json:"completion"`
}

// CompletionListData defines model for CompletionListData.
type CompletionListData struct {
	Items []Completion `json:"items"`
}

// CompletionListResponse defines model for CompletionListResponse.
type CompletionListResponse struct {
	Data CompletionListData `json:"data"`
}

// CompletionResponse defines model for CompletionResponse.
type CompletionResponse struct {
	Data CompletionData `json:"data"`
}

// CreateRecurringQuestRequest defines model for CreateRecurringQuestRequest.
type CreateRecurringQuestRequest struct {
	Description string `json:"description"`

	// SortOrder Optional display order. If omitted, the server appends to the end.
	SortOrder *int   `json:"sortOrder,omitempty"`
	Title     string `json:"title"`
}

// CreateRoomData defines model for CreateRoomData.
type CreateRoomData struct {
	InviteUrl string  `json:"inviteUrl"`
	Member    Member  `json:"member"`
	Room      Room    `json:"room"`
	Session   Session `json:"session"`
}

// CreateRoomRequest defines model for CreateRoomRequest.
type CreateRoomRequest struct {
	FinalGoal string `json:"finalGoal"`

	// FinalGoalDate Final target date for the room.
	FinalGoalDate  openapi_types.Date `json:"finalGoalDate"`
	LeaderNickname string             `json:"leaderNickname"`
	RoomName       string             `json:"roomName"`

	// Timezone IANA timezone identifier for the room.
	Timezone string `json:"timezone"`
}

// CreateRoomResponse defines model for CreateRoomResponse.
type CreateRoomResponse struct {
	Data CreateRoomData `json:"data"`
}

// DailyGoalStatus Daily goal status calculated by the server.
// The minimum required completion count is rounded from
// (active recurring quest count × dailyGoalCutoffPercent / 100).
type DailyGoalStatus string

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error Error `json:"error"`
}

// HealthData defines model for HealthData.
type HealthData struct {
	Status string `json:"status"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Data HealthData `json:"data"`
}

// InviteSummaryData defines model for InviteSummaryData.
type InviteSummaryData struct {
	RecurringQuests []RecurringQuest `json:"recurringQuests"`
	Room            Room             `json:"room"`
}

// InviteSummaryResponse defines model for InviteSummaryResponse.
type InviteSummaryResponse struct {
	Data InviteSummaryData `json:"data"`
}

// JoinInviteMemberData defines model for JoinInviteMemberData.
type JoinInviteMemberData struct {
	Member  Member  `json:"member"`
	Room    Room    `json:"room"`
	Session Session `json:"session"`
}

// JoinInviteMemberRequest defines model for JoinInviteMemberRequest.
type JoinInviteMemberRequest struct {
	Nickname string `json:"nickname"`
}

// JoinInviteMemberResponse defines model for JoinInviteMemberResponse.
type JoinInviteMemberResponse struct {
	Data JoinInviteMemberData `json:"data"`
}

// Member defines model for Member.
type Member struct {
	Id       string     `json:"id"`
	JoinedAt time.Time  `json:"joinedAt"`
	Nickname string     `json:"nickname"`
	Role     MemberRole `json:"role"`
	RoomId   string     `json:"roomId"`
}

// MemberRole defines model for Member.Role.
type MemberRole string

// MemberDailyStatus defines model for MemberDailyStatus.
type MemberDailyStatus struct {
	CompletedQuestCount int                `json:"completedQuestCount"`
	Date                openapi_types.Date `json:"date"`
	MemberId            string             `json:"memberId"`
	RequiredQuestCount  int                `json:"requiredQuestCount"`

	// Status Daily goal status calculated by the server.
	// The minimum required completion count is rounded from
	// (active recurring quest count × dailyGoalCutoffPercent / 100).
	Status                DailyGoalStatus `json:"status"`
	TotalActiveQuestCount int             `json:"totalActiveQuestCount"`
}

// PutCompletionRequest defines model for PutCompletionRequest.
type PutCompletionRequest struct {
	Note *string `json:"note"`
}

// RecurringQuest defines model for RecurringQuest.
type RecurringQuest struct {
	CreatedAt         time.Time `json:"createdAt"`
	CreatedByMemberId string    `json:"createdByMemberId"`
	Description       string    `json:"description"`
	Id                string    `json:"id"`
	IsActive          bool      `json:"isActive"`
	RoomId            string    `json:"roomId"`
	SortOrder         int       `json:"sortOrder"`
	Title             string    `json:"title"`
	UpdatedAt         time.Time `json:"updatedAt"`
}

// RecurringQuestData defines model for RecurringQuestData.
type RecurringQuestData struct {
	RecurringQuest RecurringQuest `json:"recurringQuest"`
}

// RecurringQuestListData defines model for RecurringQuestListData.
type RecurringQuestListData struct {
	Items []RecurringQuest `json:"items"`
}

// RecurringQuestListResponse defines model for RecurringQuestListResponse.
type RecurringQuestListResponse struct {
	Data RecurringQuestListData `json:"data"`
}

// RecurringQuestResponse defines model for RecurringQuestResponse.
type RecurringQuestResponse struct {
	Data RecurringQuestData `json:"data"`
}

// Room defines model for Room.
type Room struct {
	CreatedAt time.Time `json:"createdAt"`

	// DailyGoalCutoffPercent Percentage cutoff for considering a member's daily goal as met.
	// Default is 50.
	//
	// Required completed quest count is calculated by rounding
	// (active recurring quest count × dailyGoalCutoffPercent / 100).
	//
	// Example: if there are 3 active recurring quests and the cutoff is 50,
	// then 3 × 0.5 = 1.5 and the member must complete at least 2 quests.
	DailyGoalCutoffPercent int    `json:"dailyGoalCutoffPercent"`
	FinalGoal              string `json:"finalGoal"`

	// FinalGoalDate Final target date that the room is working toward.
	FinalGoalDate  openapi_types.Date `json:"finalGoalDate"`
	Id             string             `json:"id"`
	InviteToken    string             `json:"inviteToken"`
	LeaderMemberId string             `json:"leaderMemberId"`
	MemberCount    int                `json:"memberCount"`
	Name           string             `json:"name"`

	// Timezone IANA timezone identifier used to calculate each room's daily boundary.
	Timezone  string    `json:"timezone"`
	UpdatedAt time.Time `json:"updatedAt"`
}

// RoomDailyStatusData defines model for RoomDailyStatusData.
type RoomDailyStatusData struct {
	Completions     []Completion        `json:"completions"`
	Date            openapi_types.Date  `json:"date"`
	MemberStatuses  []MemberDailyStatus `json:"memberStatuses"`
	RecurringQuests []RecurringQuest    `json:"recurringQuests"`
	RoomId          string              `json:"roomId"`
}

// RoomDailyStatusResponse defines model for RoomDailyStatusResponse.
type RoomDailyStatusResponse struct {
	Data RoomDailyStatusData `json:"data"`
}

// RoomDashboardData defines model for RoomDashboardData.
type RoomDashboardData struct {
	CurrentMember    Member           `json:"currentMember"`
	Members          []Member         `json:"members"`
	RecurringQuests  []RecurringQuest `json:"recurringQuests"`
	Room             Room             `json:"room"`
	TodayCompletions []Completion     `json:"todayCompletions"`

	// TodayDate Today's date calculated in the room timezone.
	TodayDate           openapi_types.Date  `json:"todayDate"`
	TodayMemberStatuses []MemberDailyStatus `json:"todayMemberStatuses"`
}

// RoomDashboardResponse defines model for RoomDashboardResponse.
type RoomDashboardResponse struct {
	Data RoomDashboardData `json:"data"`
}

// RoomData defines model for RoomData.
type RoomData struct {
	Room Room `json:"room"`
}

// RoomListData defines model for RoomListData.
type RoomListData struct {
	Rooms []Room `json:"rooms"`
}

// RoomListResponse defines model for RoomListResponse.
type RoomListResponse struct {
	Data RoomListData `json:"data"`
}

// RoomResponse defines model for RoomResponse.
type RoomResponse struct {
	Data RoomData `json:"data"`
}

// RotateInviteTokenData defines model for RotateInviteTokenData.
type RotateInviteTokenData struct {
	InviteToken string `json:"inviteToken"`
	InviteUrl   string `json:"inviteUrl"`
}

// RotateInviteTokenResponse defines model for RotateInviteTokenResponse.
type RotateInviteTokenResponse struct {
	Data RotateInviteTokenData `json:"data"`
}

// Session defines model for Session.
type Session struct {
	ExpiresAt    time.Time `json:"expiresAt"`
	IssuedAt     time.Time `json:"issuedAt"`
	SessionToken string    `json:"sessionToken"`
}

// UpdateRecurringQuestRequest defines model for UpdateRecurringQuestRequest.
type UpdateRecurringQuestRequest struct {
	Description *string `json:"description,omitempty"`
	IsActive    *bool   `json:"isActive,omitempty"`
	SortOrder   *int    `json:"sortOrder,omitempty"`
	Title       *string `json:"title,omitempty"`
}

// UpdateRoomRequest defines model for UpdateRoomRequest.
type UpdateRoomRequest struct {
	// DailyGoalCutoffPercent Daily goal cutoff percentage.
	// The minimum required completion count is rounded from
	// (active recurring quest count × dailyGoalCutoffPercent / 100).
	DailyGoalCutoffPercent *int                `json:"dailyGoalCutoffPercent,omitempty"`
	FinalGoal              *string             `json:"finalGoal,omitempty"`
	FinalGoalDate          *openapi_types.Date `json:"finalGoalDate,omitempty"`
	RoomName               *string             `json:"roomName,omitempty"`
}

// ListCompletionsParams defines parameters for ListCompletions.
type ListCompletionsParams struct {
	From     openapi_types.Date `form:"from" json:"from"`
	To       openapi_types.Date `form:"to" json:"to"`
	QuestId  *string            `form:"questId,omitempty" json:"questId,omitempty"`
	MemberId *string            `form:"memberId,omitempty" json:"memberId,omitempty"`
}

// JoinInviteAsMemberJSONRequestBody defines body for JoinInviteAsMember for application/json ContentType.
type JoinInviteAsMemberJSONRequestBody = JoinInviteMemberRequest

// CreateRoomJSONRequestBody defines body for CreateRoom for application/json ContentType.
type CreateRoomJSONRequestBody = CreateRoomRequest

// UpdateRoomJSONRequestBody defines body for UpdateRoom for application/json ContentType.
type UpdateRoomJSONRequestBody = UpdateRoomRequest

// CreateRecurringQuestJSONRequestBody defines body for CreateRecurringQuest for application/json ContentType.
type CreateRecurringQuestJSONRequestBody = CreateRecurringQuestRequest

// UpdateRecurringQuestJSONRequestBody defines body for UpdateRecurringQuest for application/json ContentType.
type UpdateRecurringQuestJSONRequestBody = UpdateRecurringQuestRequest

// PutMyQuestCompletionJSONRequestBody defines body for PutMyQuestCompletion for application/json ContentType.
type PutMyQuestCompletionJSONRequestBody = PutCompletionRequest
